param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$failures = [System.Collections.Generic.List[string]]::new()

function Require-Text {
    param(
        [string]$RelativePath,
        [string]$Pattern,
        [string]$Message
    )

    $path = Join-Path $Root $RelativePath
    $text = Get-Content -Raw -LiteralPath $path
    if ($text -notmatch $Pattern) {
        $failures.Add("$RelativePath`: $Message")
    }
}

function Reject-Text {
    param(
        [string]$RelativePath,
        [string]$Pattern,
        [string]$Message
    )

    $path = Join-Path $Root $RelativePath
    $text = Get-Content -Raw -LiteralPath $path
    if ($text -match $Pattern) {
        $failures.Add("$RelativePath`: $Message")
    }
}

Require-Text 'src/physics-interaction/hand/Hand.h' 'struct\s+LivePalmAnchorReference' 'Dynamic grab must have an explicit live palm-anchor reference type.'
Require-Text 'src/physics-interaction/hand/Hand.h' 'tryResolveLivePalmAnchorReference' 'Dynamic grab must resolve the actual palm anchor body as the hand-side reference.'
Require-Text 'src/physics-interaction/hand/Hand.h' 'struct\s+GrabAuthorityProxyDebugSnapshot' 'Debug overlay must expose a grab authority proxy target snapshot that is not dependent on an active grab.'
Require-Text 'src/physics-interaction/hand/HandBoneColliderSet.cpp' '_latestPalmAnchorTarget\s*=\s*anchorFrame\.transform' 'Palm target must be captured from the same sampled role frame queued for the generated palm anchor.'
Require-Text 'src/physics-interaction/hand/Hand.cpp' 'Hand::tryResolveLivePalmAnchorReference[\s\S]*tryResolveLiveBodyWorldTransform\(world,\s*_handBody\.getBodyId\(\)' 'Live palm authority must read the actual palm-anchor hknp body frame.'
Require-Text 'src/physics-interaction/hand/Hand.cpp' 'Hand::getGrabAuthorityProxyDebugSnapshot\(RE::hknpWorld\* world,\s*const RE::NiTransform& rawHandWorld[\s\S]*tryResolveLivePalmAnchorReference\(world,\s*palmReference\)[\s\S]*generatedColliderFrameToGrabAuthorityFrame\(palmReference\.world\)[\s\S]*applyGrabAuthorityProxyLocalOffsetToFrame\(palmAuthorityBaseWorld,\s*_isLeft\)' 'Idle proxy debug target must show the generated/proxy-local seat point without changing the runtime proxy drive frame.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame[\s\S]*tryResolveLivePalmAnchorReference[\s\S]*livePalmAnchorMotionGrabFrame' 'Proxy authority must resolve from the live palm-anchor body frame.'
Require-Text 'src/physics-interaction/hand/HandFrame.h' 'computeGrabAuthorityProxyOffsetLocalGame[\s\S]*rockLeftGrabAuthorityProxyOffsetGameUnits[\s\S]*rockRightGrabAuthorityProxyOffsetGameUnits' 'Hidden grab authority proxy offset must be a per-hand INI-backed local offset, not a real hand-collider move.'
Reject-Text 'src/physics-interaction/hand/HandFrame.h' 'makeGrabStartupCaptureAuthorityFrame' 'Grab-start capture must not apply the configured local offset through raw hand rotation.'
Require-Text 'src/physics-interaction/hand/HandColliderTypes.h' 'generatedColliderLocalVectorToWorld[\s\S]*matrix\.entry\[0\]\[1\]\s*\*\s*localVector\.y' 'Generated collider local offsets must be applied through stored-column local space.'
Require-Text 'src/physics-interaction/hand/HandFrame.h' 'generatedProxyLocalVectorToWorld[\s\S]*generatedColliderLocalVectorToWorld\(proxyFrameWorld,\s*localVector\)[\s\S]*applyGrabAuthorityProxyLocalOffsetToFrame[\s\S]*generatedProxyLocalVectorToWorld\(proxyFrameWorld,\s*localOffset\)' 'Hidden grab authority proxy offset must be applied through generated/proxy stored-column local space.'
Reject-Text 'src/physics-interaction/hand/HandFrame.h' 'transform_math::localVectorToWorld\(proxyFrameWorld,\s*localOffset\)' 'Hidden grab authority proxy offset must not use row-axis TransformMath local-vector conversion.'
Reject-Text 'src/physics-interaction/hand/HandFrame.h' 'applyRuntimeGrabAuthorityProxyOffsetToFrame|localVectorToWorld\(rawHandWorld,\s*localOffset\)' 'Runtime proxy offset must not keep a raw-hand basis adapter.'
Reject-Text 'src/physics-interaction/hand/Hand.cpp' 'applyGrabAuthorityProxyLocalOffsetToFrame\(rawHandWorldTransform,\s*_isLeft\)' 'Startup fallback must not apply the generated/proxy local offset converter to raw controller space.'
Require-Text 'src/physics-interaction/hand/Hand.h' 'tryComputeGrabProxyLocalPalmPocketPivotAWorld' 'Proxy-local palm-pocket pivot computation must be an explicit helper so held paths do not reuse generated proxy translation.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionFrame.inl' 'tryComputeGrabProxyLocalPalmPocketFrameWorld\(hknp,\s*proxyFrameWorld\)[\s\S]*input\.grabAnchorWorld\s*=\s*proxyFrameWorld\.translate[\s\S]*closeSelectionBasisWorld\s*=\s*makeGeneratedProxyAuthorityRelationFrame\(proxyFrameWorld\)[\s\S]*input\.palmNormalWorld\s*=\s*computePalmNormalFromHandBasis\(closeSelectionBasisWorld,\s*isLeft\)[\s\S]*input\.pointingWorld\s*=\s*computePointingVectorFromHandBasis\(input\.rawHandWorld,\s*isLeft\)[\s\S]*input\.pinchDirectionWorld\s*=\s*computePinchDetectionDirectionFromHandBasis\(closeSelectionBasisWorld,\s*isLeft\)' 'Close selection must use generated/proxy origin and palm/pinch basis while far pointing remains raw/controller driven.'
Require-Text 'src/RockConfig.h' 'rockRightGrabAuthorityProxyOffsetGameUnits' 'RockConfig must expose the right-hand hidden proxy offset.'
Require-Text 'src/RockConfig.h' 'rockLeftGrabAuthorityProxyOffsetGameUnits' 'RockConfig must expose the left-hand hidden proxy offset.'
Require-Text 'src/RockConfig.cpp' 'fRightGrabAuthorityProxyOffsetXGameUnits' 'RockConfig must read the right-hand hidden proxy offset from INI.'
Require-Text 'src/RockConfig.cpp' 'fLeftGrabAuthorityProxyOffsetXGameUnits' 'RockConfig must read the left-hand hidden proxy offset from INI.'
Require-Text 'data/config/ROCK.ini' 'fRightGrabAuthorityProxyOffsetXGameUnits\s*=\s*0\.0[\s\S]*fRightGrabAuthorityProxyOffsetYGameUnits\s*=\s*-2\.0' 'Packaged INI must expose the corrected right-hand hidden proxy palm-seat offset.'
Require-Text 'data/config/ROCK.ini' 'fLeftGrabAuthorityProxyOffsetXGameUnits\s*=\s*0\.0[\s\S]*fLeftGrabAuthorityProxyOffsetYGameUnits\s*=\s*-2\.0' 'Packaged INI must expose the corrected left-hand hidden proxy palm-seat offset.'
Require-Text 'src/physics-interaction/hand/HandColliderTypes.h' 'matrixFromAxes[\s\S]*matrix\.entry\[1\]\[0\]\s*=\s*xAxis\.y[\s\S]*matrix\.entry\[0\]\[1\]\s*=\s*yAxis\.x' 'Generated hand/body colliders must keep the in-game verified column-stored native placement convention.'
Reject-Text 'src/physics-interaction/hand/HandColliderTypes.h' 'generatedColliderFrameToGrabAuthorityFrame[\s\S]*transposeStoredRotation\(colliderFrame\.rotate\)' 'Grab authority proxy must not transpose the generated palm frame; in-game proxy isolation proved that convention is wrong.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'generatedColliderFrameToGrabAuthorityFrame\(palmReference\.world\)' 'Proxy authority must pass the live palm body frame through the explicit boundary.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame[\s\S]*applyGrabAuthorityProxyLocalOffsetToFrame\(proxyBaseWorld,\s*_isLeft\)' 'Resolved hidden proxy frame must keep the generated palm base frame while applying the live offset through generated/proxy local space.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame[\s\S]*makeGrabStartupCaptureAuthorityFrame' 'Runtime hidden proxy drive must not consume the grab-start raw-rotation capture frame.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'pending\.proxyWorld\s*=\s*applyGrabAuthorityProxyLocalOffsetToFrame\(proxyBaseWorld,\s*_isLeft\)' 'Physics flush must keep the generated/proxy-local runtime offset frame instead of rebinding the proxy origin to pivot A.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame\(world,\s*handWorldTransform,\s*&handBodyWorldAtGrab,\s*proxyFrameWorldAtGrab[\s\S]*grabAuthorityPivotAWorld\s*=\s*proxyFrameWorldAtGrab\.translate[\s\S]*palmPocketPivotAWorld\s*=\s*proxyFrameWorldAtGrab\.translate[\s\S]*grabPivotAForPrimaryChoice\s*=\s*palmPocketPivotAWorld' 'Grab commit must resolve the live proxy frame once, then use that same generated/proxy palm-pocket point for mesh/contact evidence selection.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'The hidden proxy is body A[\s\S]*RE::NiPoint3\s+grabPivotAWorld\s*=\s*palmPocketPivotAWorld[\s\S]*freezeGrabAuthorityFrame<RE::NiTransform>[\s\S]*\.proxyWorld\s*=\s*proxyFrameWorldAtGrab[\s\S]*\.pivotAWorld\s*=\s*grabPivotAWorld[\s\S]*applyFrozenGrabAuthorityFrameToGrabFrame\(_grabFrame,\s*frozenAuthorityFrame\)[\s\S]*createProxyConstraintGrabDrive\(\s*bhkWorld,\s*world,\s*objectBodyId,\s*proxyFrameWorldAtGrab,\s*handWorldTransform,\s*grabPivotAWorld' 'Committed body-A proxy must keep the resolved proxy frame, freeze pivot A separately, and create the constraint from that coherent body-local authority frame.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'palmPocketPivotAWorld\s*=\s*proxyFrameWorldAtGrab\.translate' 'Close grab palm-pocket acquisition must seed from the already resolved generated/proxy startup point.'
Require-Text 'src/physics-interaction/hand/Hand.cpp' 'Hand::computeGrabPivotAWorld[\s\S]*tryComputeGrabProxyLocalPalmPocketFrameWorld\(world,\s*proxyFrameWorld\)[\s\S]*return\s+proxyFrameWorld\.translate' 'Pivot-A fallback helper must use the shared generated/proxy palm-pocket frame before falling back to raw translation.'
Require-Text 'src/physics-interaction/hand/Hand.cpp' 'Hand::tryComputeGrabProxyLocalPalmPocketFrameWorld[\s\S]*generatedColliderFrameToGrabAuthorityFrame\(palmReference\.world\)[\s\S]*applyGrabAuthorityProxyLocalOffsetToFrame\(palmAuthorityBaseWorld,\s*_isLeft\)' 'Proxy-local palm-pocket frame capture must apply the configured offset through generated/proxy local space.'
Require-Text 'src/physics-interaction/hand/Hand.cpp' 'Hand::tryComputeGrabProxyLocalPalmPocketPivotAWorld[\s\S]*tryComputeGrabProxyLocalPalmPocketFrameWorld\(world,\s*proxyFrameWorld\)[\s\S]*outPivotWorld\s*=\s*proxyFrameWorld\.translate' 'Proxy-local palm-pocket pivot capture must delegate to the shared generated/proxy frame helper.'
Reject-Text 'src/physics-interaction/hand/Hand.cpp' 'computeGrabStartupCapturePivotAWorld' 'Committed grab capture must not retain a raw-fallback startup pivot helper.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame[\s\S]*rootFlattenedPalmAnchorTarget' 'Proxy authority must not use the sampled palm target as the active body-A frame.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame[\s\S]*rawHandFallback' 'Proxy authority must not silently fall back to raw controller space.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'freezeGrabAuthorityFrame<RE::NiTransform>[\s\S]*\.proxyWorld\s*=\s*proxyFrameWorldAtGrab[\s\S]*\.pivotAWorld\s*=\s*grabPivotAWorld' 'Grab-start hand/object relation must freeze the resolved proxy frame and the selected pivot A as separate pieces of the authority contract.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'objectToBodyAtGrab\s*=\s*computeRuntimeBodyLocalTransform\(objectWorldTransform,\s*grabBodyWorldAtGrab\)' 'Proxy authority must preserve the visual-object to hknp BODY relation captured at grab time.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'constraintUsesMotionBodyAtGrab\s*=\s*false' 'Proxy authority must keep hknp constraint body-B data in the rigid BODY frame.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'constraintBodyWorldAtGrab\s*=\s*grabBodyWorldAtGrab' 'Proxy authority must encode transform-B and angular target data against the BODY frame, not MOTION/COM.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'objectToConstraintBodyAtGrab' 'Proxy authority cleanup must remove the stale solver-local object relation capture.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'applyFrozenGrabAuthorityFrameToGrabFrame[\s\S]*frame\.bodyLocal\s*=\s*frozen\.bodyLocal' 'Proxy authority must store the captured visual-object to BODY relation through the frozen authority frame instead of assuming BODY equals the visible node.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' '_grabFrame\.constraintBodyLocal' 'Proxy authority cleanup must remove the retired duplicate solver-local BODY relation.'
Require-Text 'src/physics-interaction/grab/GrabCore.h' 'desiredBodyWorld\s*=\s*input\.hasDesiredBodyWorld\s*\?\s*input\.desiredBodyWorld\s*:[\s\S]*shiftObjectToAlignGripWithPocket\(\s*input\.bodyWorld,\s*input\.pivotAWorld,\s*input\.gripPointWorld\)' 'Proxy authority must derive the solver BODY target from explicit BODY authority or BODY-frame pocket alignment, not from the visual object frame.'
Reject-Text 'src/physics-interaction/grab/GrabCore.h' 'desiredBodyWorld\s*=\s*transform_math::composeTransforms\(frozen\.desiredObjectWorld,\s*frozen\.bodyLocal\)' 'Proxy authority must not let the visual object relation define the solver BODY target.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'desiredBodyWorld\s*=\s*grab_frame_math::shiftObjectToAlignGripWithPocket\(\s*grabBodyWorldAtGrab,\s*grabPivotAWorld,\s*grabGripPoint\)[\s\S]*desiredObjectWorld\s*=\s*deriveNodeWorldFromBodyWorld\(desiredBodyWorld,\s*objectToBodyAtGrab\)' 'Generic grab capture must build the solver BODY target first and derive the visual object target from the captured BODY relation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'freezeGrabAuthorityFrame<RE::NiTransform>[\s\S]*\.desiredObjectWorld\s*=\s*desiredObjectWorld,[\s\S]*\.desiredBodyWorld\s*=\s*desiredBodyWorld,[\s\S]*\.hasDesiredObjectWorld\s*=\s*true,[\s\S]*\.hasDesiredBodyWorld\s*=\s*true' 'Grab capture must pass an explicit BODY authority target into the frozen frame contract.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'desiredConstraintBodyWorld' 'Proxy authority cleanup must remove the retired constraint-space desired BODY target.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' '_grabFrame\.(constraintHandSpace|constraintBodyHandSpace)' 'Proxy authority cleanup must remove retired constraint-space capture fields.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'convertNativeBodyReadbackToConventionalObjectFrame|constraintConventionalBodyHandSpace|desiredConventionalBodyWorld' 'Proxy authority must not retain removed conventional angular candidates.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveProxyConstraintAngularDriveTargetWorld|makeNativeAngularBoundaryTargetFromVisualTarget|applyProxyConstraintAngularVelocityDrive' 'Proxy authority must not retain the removed direct angular velocity drive.'
Require-Text 'src/physics-interaction/grab/GrabConstraint.cpp' 'setGrabMotorAtomsActive\(header,\s*true,\s*true\)' 'Proxy angular authority must always enable the ragdoll atom motor.'
Require-Text 'src/physics-interaction/hand/HandFrame.h' 'makeGeneratedProxyAuthorityRelationFrame[\s\S]*transposeStoredRotation\(proxyFrameWorld\.rotate\)' 'Generated/proxy object relation math must use a row-view of the generated stored-column palm frame.'
Require-Text 'src/physics-interaction/grab/GrabCore.h' 'objectInGeneratedProxyLocalSpace[\s\S]*generatedColliderWorldPointToLocal\(proxyWorld,\s*objectWorld\.translate\)[\s\S]*generatedColliderWorldVectorToLocal\(proxyRotationWorld,\s*objectAxisXWorld\)' 'Proxy authority must convert BODY/object relations through the same stored-column generated collider local-space boundary used by pivot A.'
Require-Text 'src/physics-interaction/grab/GrabCore.h' 'objectFromGeneratedProxyLocalSpace[\s\S]*generatedColliderLocalVectorToWorld\(proxyWorld,\s*objectProxyLocal\.translate\)[\s\S]*generatedColliderLocalVectorToWorld\(proxyRotationWorld,\s*objectAxisXProxyLocal\)' 'Proxy authority must replay BODY/object relations through the same stored-column generated collider world-space boundary used by generated bodies.'
Require-Text 'src/physics-interaction/grab/GrabCore.h' 'proxyAuthorityBodyHandSpace\s*=[\s\S]*objectInGeneratedProxyLocalSpace\(input\.proxyWorld,\s*frozen\.desiredBodyWorld\)[\s\S]*frozen\.desiredBodyWorld\s*=[\s\S]*objectFromGeneratedProxyLocalSpace\(input\.proxyWorld,\s*frozen\.proxyAuthorityBodyHandSpace\)' 'Grab capture must freeze and replay BODY authority through generated/proxy collider-local space, not plain row-axis inverse math.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'applyFrozenGrabAuthorityFrameToGrabFrame[\s\S]*frame\.proxyAuthorityHandSpace\s*=\s*frozen\.proxyAuthorityHandSpace' 'Proxy authority must capture object relation in generated/proxy authority space through the frozen authority contract.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'applyFrozenGrabAuthorityFrameToGrabFrame[\s\S]*frame\.proxyAuthorityBodyHandSpace\s*=\s*frozen\.proxyAuthorityBodyHandSpace' 'Proxy authority must capture BODY relation in the same generated/proxy authority space used by the live angular target.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'kGrabObjectRotationReferenceName\s*=\s*"generatedProxyAuthorityLocal"' 'The generated/proxy authority relation must be the only production dynamic-grab rotation reference.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'rockGrabObjectRotationReferenceMode|grabObjectRotationReferenceModeName|legacyBody|convertedBodyCapture|splitVisualNativeBoundary' 'Proxy authority must not keep the removed selectable rotation modes.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'createProxyConstraintGrabDrive\(\s*bhkWorld,\s*world,\s*objectBodyId,\s*proxyFrameWorldAtGrab' 'Proxy constraint creation must use the resolved palm-frame proxy transform.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'constraintPivotAWorld\s*=\s*grabPivotAWorld[\s\S]*pivotAProxyLocalGame\s*=\s*grab_constraint_math::computeGeneratedProxyConstraintPivotLocalGame\(proxyWorldTransform,\s*constraintPivotAWorld\)[\s\S]*createGrabConstraint\(world,[\s\S]*proxyWorldTransform,[\s\S]*constraintPivotAWorld' 'Proxy constraint creation must keep the proxy body at its offset frame and encode pivot A as an explicit generated/proxy local point on body A.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'desiredBodyWorldAtCreation\s*=[\s\S]*objectFromGeneratedProxyLocalSpace\(proxyWorldTransform,\s*_grabFrame\.proxyAuthorityBodyHandSpace\)[\s\S]*desiredBodyTransformProxySpace\s*=[\s\S]*objectInGeneratedProxyLocalSpace\(proxyWorldTransform,\s*desiredBodyWorldAtCreation\)' 'Proxy constraint creation must seed the ragdoll angular target through generated/proxy collider-local BODY relation processing.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'createProxyConstraintGrabDrive[\s\S]*desiredBodyTransformProxySpace\s*=\s*_grabFrame\.constraintBodyHandSpace' 'Proxy constraint creation must not seed the ragdoll angular target from the older constraint-space relation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'solverPivotBConstraintLocalGame\s*=\s*_grabFrame\.pivotBConstraintLocalGame' 'Proxy constraint creation must preserve the frozen selected BODY-local pivot for grab/release semantics.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'solverPivotBConstraintLocalGame\s*=\s*grab_constraint_math::computeDynamicTransformBTranslationGame' 'Proxy constraint creation must not replace the selected BODY-local pivot with a generated/proxy relation-implied pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'selectedPivotBBodyLocalGame\s*=\s*activeProxyConstraintPivotBLocalGame\(\)[\s\S]*relationPivotB\s*=[\s\S]*computeHiggsTransformBTranslationGame\([\s\S]*outActivePivotBBodyLocalGame\s*=\s*relationPivotB' 'Proxy constraint target math must keep the selected pivot separately while feeding the active transform-B translation from the HIGGS relation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'updateProxyConstraintGrabDriveTarget[\s\S]*pivotAProxyLocalGame\s*=\s*_grabAuthorityPivotAProxyLocalGame[\s\S]*ragdollDecompositionMode[\s\S]*writeGrabConstraintHeldTargetAtoms\(\s*transformBRotation,\s*transformBTranslation,\s*targetBRca,[\s\S]*desiredBodyTransformProxySpace,[\s\S]*pivotAProxyLocalGame[\s\S]*ragdollDecompositionMode' 'Proxy held updates must hot-swap transform-B decomposition while keeping target_bRca and transform-B translation derived from the frozen generated/proxy local pivot.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'updateProxyConstraintGrabDriveTarget[\s\S]*transformAPos\[0\]\s*=' 'Proxy held updates must not rewrite transform-A; body A carries the frozen local pivot while the proxy body moves in world space.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'tryGetGrabDriveObjectWorldTransform[\s\S]*return\s+tryGetGrabAuthorityBodyWorldTransform\(world,\s*bodyId,\s*outTransform\)' 'Proxy runtime error and pivot telemetry must read body-B through the BODY grab-authority frame.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'outDesiredObjectWorld\s*=[\s\S]*objectFromGeneratedProxyLocalSpace\(proxyWorldTransform,\s*_grabFrame\.proxyAuthorityHandSpace\)[\s\S]*outDesiredBodyWorld\s*=[\s\S]*objectFromGeneratedProxyLocalSpace\(proxyWorldTransform,\s*desiredBodyRelationProxySpace\)[\s\S]*desiredBodyTransformProxySpace\s*=[\s\S]*objectInGeneratedProxyLocalSpace\(proxyWorldTransform,\s*outDesiredBodyWorld\)' 'Proxy desired object, BODY target, and angular atom input must use generated/proxy collider-local processing.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveGrabAuthorityProxyFrame\(world,\s*handWorldTransform,\s*nullptr,\s*proxyAuthorityWorld,\s*proxyAuthoritySource\)[\s\S]*queueProxyGrabAuthorityTarget\(\s*proxyAuthorityWorld' 'Held updates must queue the resolved hidden proxy frame directly instead of rebinding the proxy origin to pivot A.'
Require-Text 'src/physics-interaction/hand/HandFrame.h' 'generatedProxyLocalPointToWorld[\s\S]*generatedProxyLocalVectorToWorld\(proxyFrameWorld,\s*localPoint\)' 'Generated/proxy local pivot replay must share the stored-column local vector converter.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'resolveActiveGrabAuthorityPivotAWorld\(\s*const RE::NiTransform& proxyWorldTransform[\s\S]*_grabFrame\.pivotAHandBodyLocalGame[\s\S]*generatedProxyLocalPointToWorld\(proxyWorldTransform,\s*_grabFrame\.pivotAHandBodyLocalGame\)' 'Held pivot A must replay the frozen generated/proxy local pivot instead of recomputing palm or pinch seats.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'pinchPivotRawHandLocal|localPointToWorld\(rawHandWorldTransform' 'Pinch-pocket held pivot replay must not use raw hand local space.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'queueGeneratedKeyframedBodyTarget\(\s*_grabAuthorityProxyDriveState,\s*pending\.proxyWorld' 'Proxy authority must queue the active pocket-origin proxy frame through the generated keyframed-body drive path.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'driveGeneratedKeyframedBody\([\s\S]*_grabAuthorityProxy[\s\S]*"grab-authority-proxy"' 'Proxy authority must move with the same native generated-body drive path as the actual palm collider.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'tryResolveLiveBodyWorldTransform\(world,\s*proxyBodyId,\s*proxyReadbackBetween' 'Proxy readback telemetry must inspect the same live frame shown by the visual debug overlay.'
Require-Text 'src/RockConfig.h' 'rockDebugGrabTimelineTrace[\s\S]*rockDebugGrabTimelineTraceIntervalFrames' 'RockConfig must expose structured grab timeline tracing and interval control.'
Require-Text 'src/RockConfig.cpp' 'bDebugGrabTimelineTrace[\s\S]*iDebugGrabTimelineTraceIntervalFrames' 'RockConfig must read structured grab timeline tracing from INI.'
Require-Text 'data/config/ROCK.ini' 'bDebugGrabTimelineTrace\s*=\s*false[\s\S]*iDebugGrabTimelineTraceIntervalFrames\s*=\s*1' 'Packaged ROCK.ini must expose structured grab timeline tracing disabled by default.'
Require-Text 'src/RockConfig.h' 'rockGrabRagdollDecompositionMode' 'RockConfig must expose the grab ragdoll decomposition hot-swap mode.'
Require-Text 'src/RockConfig.cpp' 'iGrabRagdollDecompositionMode[\s\S]*rockGrabRagdollDecompositionMode\s*<\s*0[\s\S]*rockGrabRagdollDecompositionMode\s*>\s*1' 'RockConfig must read and clamp the grab ragdoll decomposition hot-swap mode.'
Require-Text 'data/config/ROCK.ini' 'iGrabRagdollDecompositionMode\s*=\s*1' 'Packaged ROCK.ini must expose the grab ragdoll decomposition hot-swap mode.'
Require-Text 'src/physics-interaction/grab/GrabCore.h' 'traceId[\s\S]*traceTargetWriteSequence' 'Canonical grab frame must carry a stable trace id and target-write sequence for timeline correlation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'nextGrabTimelineTraceId[\s\S]*GRAB_TRACE stage=attempt[\s\S]*GRAB_TRACE stage=capture[\s\S]*GRAB_TRACE stage=capture_frames[\s\S]*GRAB_TRACE stage=capture_basis' 'Grab timeline trace must connect grab attempt and capture evidence under one trace id.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'GRAB_TRACE stage=constraint_create[\s\S]*GRAB_TRACE stage=constraint_atoms[\s\S]*GRAB_TRACE stage=target_write[\s\S]*GRAB_TRACE stage=pre_solve[\s\S]*GRAB_TRACE stage=after_solve[\s\S]*GRAB_TRACE stage=release' 'Grab timeline trace must cover constraint creation, atom writes, target writes, pre-solve, after-solve, and release.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'observeCustomGrabAuthorityAfterSolve[\s\S]*const bool debugGrabFrameLogging[\s\S]*const bool timelineTraceLogging[\s\S]*const bool shouldSampleForAnomaly[\s\S]*if \(!debugGrabFrameLogging && !timelineTraceLogging && !shouldSampleForAnomaly\)' 'Proxy after-solve anomaly sampling and timeline tracing must not require verbose grab-frame logging.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'computeGrabPalmBasisDelta[\s\S]*xAxisDegrees[\s\S]*yAxisDegrees[\s\S]*zAxisDegrees[\s\S]*rawDeterminant[\s\S]*proxyDeterminant' 'Proxy telemetry must expose raw-hand to generated-palm per-axis basis deltas and handedness determinants.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'PROXY GRAB PALM BASIS MISMATCH[\s\S]*axisDeg=\(\{:\.1f\},\{:\.1f\},\{:\.1f\}\)[\s\S]*determinant=\(\{:\.3f\},\{:\.3f\}\)' 'Grab-start palm basis telemetry must report per-axis raw/proxy deltas before constraint creation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'PROXY GRAB FRAME MISMATCH[\s\S]*rawToProxyTarget[\s\S]*targetAxisDeg[\s\S]*liveAxisDeg[\s\S]*determinantTarget[\s\S]*targetToHiggsRelation[\s\S]*transformBFrozenDelta[\s\S]*pivotBRelationDelta' 'Proxy after-solve telemetry must expose the raw/proxy frame mismatch, palm-basis axes, and HIGGS relation constraint-frame invariants without relying on verbose grab logging.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'pivotARoundTrip=\{:\.3f\}gu' 'Proxy after-solve telemetry must report whether the old transform-A world/local round-trip would have moved the frozen solver pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'RAGDOLL ANGULAR PROBE[\s\S]*beforeErr[\s\S]*afterErr[\s\S]*reduce[\s\S]*axisDot[\s\S]*forceA[\s\S]*targetToHiggsRelation[\s\S]*transformBFrozenDelta[\s\S]*pivotBRelationDelta[\s\S]*gripBefore[\s\S]*pivotLever[\s\S]*linTorque[\s\S]*linTorqueDotReq[\s\S]*linTorqueAxisProxy' 'Proxy after-solve telemetry must prove whether the ragdoll angular atom reduces body rotation error independently from the linear pivot and whether target_bRca/transform-B translation match the HIGGS proxy-in-BODY relation.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'computeHardKeyframeVelocityForTarget\(\s*world,\s*proxyBodyId,\s*pending\.proxyWorld,\s*driveDelta,[\s\S]*angularVelocityHavok\)' 'Proxy authority may keep FO4VR hard-keyframe velocity as diagnostic fallback when palm motion velocity is unavailable.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'ComputeHardKeyFrame_t[\s\S]*offsets::kFunc_ComputeHardKeyFrame' 'Proxy telemetry may use FO4VR native hard-keyframe velocity when palm motion velocity is unavailable.'
Require-Text 'src/physics-interaction/grab/GrabConstraintMath.h' 'writeGrabConstraintAngularDecomposition[\s\S]*kGrabRagdollDecompositionModeRelationTransformB[\s\S]*writeHavokRotationColumns\(transformBRotation,\s*transformBRelation\)[\s\S]*writeHavokRotationRows\(targetBRca,\s*proxyInBody\.rotate\)' 'FO4VR custom grab angular setup must centralize the mode-selectable transform-B decomposition while target_bRca keeps the proxy-in-BODY relation.'
Require-Text 'src/physics-interaction/grab/GrabConstraintMath.h' 'writeGrabConstraintHeldTargetAtoms\(\s*float\*\s*transformBRotation[\s\S]*writeGrabConstraintAngularDecomposition\(transformBRotation,\s*targetBRca,\s*proxyInBody,\s*decompositionMode\)[\s\S]*computeHiggsTransformBTranslationGameFromProxyInBody' 'FO4VR custom grab held updates must rewrite the hot-swappable transform-B decomposition plus current proxy-in-BODY target and relation-derived transform-B translation.'
Reject-Text 'src/physics-interaction/grab/GrabConstraintMath.h' 'writeHavokRotationRows\(transformBRotation' 'Proxy angular setup must keep transform-B in Havok column storage.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'driveQueuedTargets\s*=\s*_grabAuthorityProxyQueuedSequence' 'Held telemetry must report proxy queue counters when proxy authority is active.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'driveFlushedTargets\s*=\s*_grabAuthorityProxyFlushSequence' 'Held telemetry must report proxy flush counters when proxy authority is active.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'grabPivotAForPrimaryChoice\s*=\s*palmPocketPivotAWorld' 'Close-grab primary body choice must use the generated/proxy-local palm-pocket acquisition pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'acquisitionGrabPivotAWorld\s*=\s*palmPocketPivotAWorld' 'Three-phase acquisition must use the same generated/proxy-local palm-pocket acquisition pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'buildGrabPocketFrameWithPalmCenter\(\s*proxyAuthorityFrameWorldAtGrab,\s*_isLeft,\s*acquisitionGrabPivotAWorld' 'Palm-pocket mesh acquisition must build orientation from generated/proxy authority space and position from the resolved proxy-origin acquisition pivot.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'buildGrabPocketFrameWithPalmCenter\(\s*handWorldTransform' 'Dynamic grab pocket orientation must not be rebuilt from the raw hand/controller basis.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'buildRuntimeGrabContactPatch\([\s\S]*acquisitionGrabPivotAWorld[\s\S]*canonicalPivotPointWorld' 'Contact patch candidate scoring must consume the resolved proxy-origin acquisition pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'fingerEvidenceSurfaceHit\.pivotToSurfaceDistanceGameUnits\s*=\s*pointDistanceGameUnits\(palmPocketPivotAWorld,\s*fingerEvidencePointWorld\)' 'Finger evidence telemetry must measure against the generated/proxy-local palm-pocket acquisition pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'palmTangentWorld\s*=\s*acquisitionPocket\.fingerForwardWorld[\s\S]*palmBitangentWorld\s*=\s*acquisitionPocket\.crossPalmWorld' 'Contact-patch probing must share the generated/proxy palm-pocket basis instead of rebuilding a mismatched tangent frame.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'livePivotAWorld\s*=\s*proxyAuthorityWorld\.translate' 'Seated palm-pocket reacquire must not fall back to the generated proxy origin as the pocket pivot.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'tryComputeGrabProxyLocalPalmPocketPivotAWorld\(world,\s*livePivotAWorld\)[\s\S]*buildGrabPocketFrameWithPalmCenter\([\s\S]*livePivotAWorld[\s\S]*findSeatedGrabPivotNearPalmPocket\([\s\S]*livePivotAWorld' 'Seated palm-pocket reacquire must search from the current generated/proxy-local palm-pocket pivot.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'supportPivotAWorld|refreshHeldAuthoritySupport|evaluateHeldSupportRefresh' 'Held support refresh must stay removed; TouchHeld authority is frozen until release.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'drawGrabAuthorityProxy[\s\S]*getGrabAuthorityProxyDebugSnapshot\(hknp,\s*rawHandWorld,\s*snapshot\)[\s\S]*RightGrabAuthorityProxyTarget' 'Proxy overlay must draw the computed grab-start capture frame before a grab creates a readback proxy body.'
Require-Text 'src/physics-interaction/debug/DebugBodyOverlay.h' 'enum class\s+AxisOverlayBasis[\s\S]*StoredColumns' 'Proxy/palm overlay must expose a stored-column axis mode for generated collider seating checks.'
Require-Text 'src/physics-interaction/debug/DebugBodyOverlay.cpp' 'entry\.basis\s*==\s*AxisOverlayBasis::StoredColumns[\s\S]*storedColumnAxis\(entry\.transform\.rotate,\s*0\)' 'Generated palm seating axes must draw the authored collider columns, not the generic Ni local-vector view.'
Require-Text 'src/physics-interaction/hand/Hand.h' 'tryGetPalmAnchorTarget\(RE::NiTransform& outTarget\)\s+const' 'Proxy debug overlay must be able to draw the live generated palm target before relying on body readback.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'addGrabAuthorityAxisReference[\s\S]*tryGetPalmAnchorTarget\(palmAnchorTarget\)[\s\S]*addStoredColumnAxisTransform\([\s\S]*RightGrabPalmGeneratedDirect' 'Proxy overlay must include the generated palm XYZ marker in the same view as the proxy target/readback markers.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'outDesiredObjectWorld\s*=\s*multiplyTransforms\(proxyWorldTransform,\s*_grabFrame\.rawHandSpace\)' 'Proxy body-A convention must not use the raw controller hand-space relation.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'desiredBodyTransformRawHandSpace|initialDesiredBodyWorld\s*=\s*multiplyTransforms\(handWorldTransform' 'Proxy diagnostics must not retain the retired raw desired-BODY composition.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' '_grabFrame\.bodyLocal\s*=\s*makeIdentityTransform\(\)' 'Proxy authority must not erase the visual-object to BODY relation; doing so causes immediate angular correction after grab.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'constraintBodyWorldAtGrab\s*=\s*constraintUsesMotionBodyAtGrab\s*\?\s*motionBodyWorldAtGrab\s*:\s*grabBodyWorldAtGrab' 'Proxy authority must not route body-B constraint data through MOTION/COM.'
Reject-Text 'src/physics-interaction/grab/GrabConstraintMath.h' 'writeHavokRotationRows\(transformBRotation' 'Proxy angular setup must keep transform-B in Havok column storage while target_bRca carries the constraint-frame residual.'
Reject-Text 'src/physics-interaction/grab/GrabAuthorityProxyMotion.h' 'computeAngularVelocityRadiansPerSecond|matrixColumn|axisSum' 'The old manual matrix-column proxy angular helper must stay removed; proxy angular telemetry uses the FO4VR hard-keyframe helper only as fallback.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'computeAngularVelocityRadiansPerSecond\(previousProxyWorld,\s*pending\.proxyWorld,\s*driveDelta,\s*angularVelocityHavok\)' 'Proxy authority must not return to the old matrix-column angular delta helper.'
Reject-Text 'src/physics-interaction/hand/HandGrab.cpp' 'proxyDrive=exactZeroVelocity' 'Proxy authority must not return to the sampled-target exact-zero-velocity drive policy.'

if ($failures.Count -gt 0) {
    Write-Host 'Grab authority proxy frame source test failed:'
    foreach ($failure in $failures) {
        Write-Host " - $failure"
    }
    exit 1
}

Write-Host 'Grab authority proxy frame source test passed.'
