param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$failures = [System.Collections.Generic.List[string]]::new()

function Require-Text {
    param([string]$Path, [string]$Pattern, [string]$Message)

    $fullPath = Join-Path $Root $Path
    if (-not (Test-Path -LiteralPath $fullPath)) {
        $failures.Add($Message)
        return
    }
    if ((Get-Content -Raw -LiteralPath $fullPath) -notmatch $Pattern) {
        $failures.Add($Message)
    }
}

function Reject-Text {
    param([string]$Path, [string]$Pattern, [string]$Message)

    $fullPath = Join-Path $Root $Path
    if ((Test-Path -LiteralPath $fullPath) -and (Get-Content -Raw -LiteralPath $fullPath) -match $Pattern) {
        $failures.Add($Message)
    }
}

# The new diagnostic suite has its own master and subordinate switches. The
# legacy straight/pad overlay remains a separate switch and cannot implicitly
# enable or disable swept-arc capture.
foreach ($path in @('data/config/ROCK.ini', 'data/mod/ROCK_Config/ROCK.ini')) {
    Require-Text $path 'NEW SWEPT-ARC FINGER SOLVER VISUALIZATION' 'Swept-arc visualization must have a clearly separated INI block.'
    Require-Text $path 'bDebugShowGrabFingerSweptArc\s*=\s*false' 'Reference INIs must expose the swept-arc master switch disabled by default.'
    Require-Text $path 'bDebugShowGrabFingerSweptArcText\s*=\s*true' 'Reference INIs must expose swept-arc labels independently.'
    Require-Text $path 'bDebugShowGrabFingerSweptArcLiveSkeleton\s*=\s*true' 'Reference INIs must expose live-skeleton comparison independently.'
    Require-Text $path 'LEGACY ONLY:[\s\S]*bDebugShowGrabFingerProbes\s*=\s*false' 'Reference INIs must identify the unrelated legacy probe switch.'
}
Require-Text 'src/RockConfig.cpp' '"bDebugShowGrabFingerSweptArc"' 'Runtime config must load the swept-arc master switch.'
Require-Text 'src/RockConfig.cpp' '"bDebugShowGrabFingerSweptArcText"' 'Runtime config must load the swept-arc label switch.'
Require-Text 'src/RockConfig.cpp' '"bDebugShowGrabFingerSweptArcLiveSkeleton"' 'Runtime config must load the swept-arc skeleton switch.'

# Capture is generated by the one-shot indexed solve and stored object-local.
# Overlay publication only transforms the fixed payload; it must never invoke
# the geometric solver or BVH query itself.
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'struct FingerSweepDebugCapture' 'Swept-arc diagnostics must use a dedicated fixed capture payload.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'probePointsObjectLocal' 'Swept-arc paths must be stored object-local so they follow the held object.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'contactCenterObjectLocal' 'The exact selected contact sphere center must be captured.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'selectedProbeIndex' 'The selected tip/outer/inner probe must be captured.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'spatialNodeVisits' 'BVH node visit totals must be exposed for diagnosis.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' 'rockDebugShowGrabFingerSweptArc\s*\?\s*&sweepDebugCapture\s*:\s*nullptr' 'Only the new master switch may request one-shot swept capture.'
Require-Text 'src/physics-interaction/hand/HandGrab.cpp' '_grabFingerSweepDebugObjectWorld\s*=\s*desiredObjectWorld' 'Captured object-local arcs must track the commanded held-object transform.'

$overlayPath = Join-Path $Root 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl'
$overlayText = Get-Content -Raw -LiteralPath $overlayPath
$sweepStart = $overlayText.IndexOf('if (drawFingerSweptArc)')
$legacyStart = $overlayText.IndexOf('if (drawFingerProbes)', $sweepStart + 1)
if ($sweepStart -lt 0 -or $legacyStart -le $sweepStart) {
    $failures.Add('Swept-arc overlay must be a distinct block before the legacy probe overlay.')
} else {
    $sweepBlock = $overlayText.Substring($sweepStart, $legacyStart - $sweepStart)
    if ($sweepBlock -match 'drawFingerProbes|rockDebugShowGrabFingerProbes') {
        $failures.Add('Swept-arc overlay must not depend on the legacy probe switch.')
    }
    if ($sweepBlock -match 'solveGrabFingerPoseFromTriangles|querySphereWorld') {
        $failures.Add('Overlay publication must never re-solve geometry or query the BVH.')
    }
}

Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'GrabFingerSweepTip' 'Overlay must draw the actual Tip arc.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'GrabFingerSweepOuter' 'Overlay must draw the actual Outer arc.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'GrabFingerSweepInner' 'Overlay must draw the actual Inner arc.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'fingerSweepDebugStateName' 'Overlay must label hit, fallback, reach, close-limit, and over-open states.'
Require-Text 'src/physics-interaction/core/PhysicsInteractionDebugOverlay.inl' 'release and grab again \(pinch is intentionally excluded\)' 'Overlay must explain missing one-shot capture and pinch exclusion.'
Reject-Text 'src/physics-interaction/debug/DebugBodyOverlay.cpp' 'case MarkerOverlayRole::GrabFingerSweepTip:[\s\S]{0,250}color\[3\]\s*=\s*0\.0f' 'Swept-arc probe colors must remain visible.'

if ($failures.Count -gt 0) {
    Write-Host 'Grab finger swept-arc debug boundary failed:'
    foreach ($failure in $failures) {
        Write-Host " - $failure"
    }
    exit 1
}

Write-Host 'Grab finger swept-arc debug boundary passed.'
