# Purity + lockstep invariants for the grab pose objective
# (src/physics-interaction/grab/GrabPoseObjective.h). The header must stay a
# pure, deterministic function of its inputs: it ships the objective that was
# fitted offline, and any impurity (RNG, logging, global config reads) breaks
# either determinism of the solved seat or the fixture parity with the offline
# harness.

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$failures = [System.Collections.Generic.List[string]]::new()

function Require-Text([string]$Path, [string]$Pattern, [string]$Message) {
    $text = Get-Content -Raw -LiteralPath (Join-Path $Root $Path)
    if ($text -notmatch $Pattern) {
        $failures.Add($Message)
    }
}

function Reject-Text([string]$Path, [string]$Pattern, [string]$Message) {
    $text = Get-Content -Raw -LiteralPath (Join-Path $Root $Path)
    if ($text -match $Pattern) {
        $failures.Add($Message)
    }
}

$header = 'src/physics-interaction/grab/GrabPoseObjective.h'

# --- Purity: deterministic, silent, config-free --------------------------------

Reject-Text $header '\brand\(|std::mt19937|<random>|rand_r|srand' 'The pose solve must be deterministic: identical inputs must always produce the identical seat. No RNG of any kind.'
Reject-Text $header 'ROCK_LOG|spdlog|printf|std::cout' 'The objective header is pure math consumed at grab time; logging belongs to the caller that owns rate-limiting and context.'
Reject-Text $header 'g_rockConfig' 'The header must not read global config: weights/constants/thresholds arrive as explicit parameters so the objective stays testable and the fit provenance stays visible.'
Reject-Text $header 'std::chrono|time\(|clock\(' 'No time sources: solve behavior must not vary run to run.'

# --- Fitted provenance stays visible -------------------------------------------

Require-Text $header '2026-07-26-grab-pose-objective-fit\.md' 'The header must cite the fit document: the weights and constants are measured/fitted values, and a future reader must be able to re-verify them instead of trusting bare numbers.'
Require-Text $header 'struct ObjectiveWeights[\s\S]*touch = 145\.2505f' 'The shipped default weights must be the fitted values (2026-08-01 round 3); changing them requires a refit, not a hand tweak.'
Reject-Text $header 'float contacts\s*=|float oppose\s*=|float enclose\s*=|float balance\s*=' 'contacts/oppose/enclose/balance fitted to ~zero across independent rounds and were deliberately deleted; dead terms stay deleted, not dormant.'

# --- One-sided term structure (first-contact-stop invariant) -------------------

Require-Text $header 'touchRaw = \(std::max\)\(0\.0f, minGap\)' 'touch must be one-sided: contact is a CONSTRAINT (first-contact-stop), never an inward pull that rewards pressing objects into the palm.'
Require-Text $header 'palmRaw = \(std::max\)\(0\.0f, palmGap - constants\.palmSlackGameUnits\)' 'palmProx must be one-sided with slack: the surface may float off the palm without penalty up to the slack, and pressing in earns nothing.'
Reject-Text $header 'gap \+ 0\.4|TARGET_CONTACT|PEN_TARGET' 'Symmetric contact/penetration targets are the round-2 design that shoved thin objects into the palm; they must not come back.'

# --- Arrival-continuity solve --------------------------------------------------

Require-Text $header 'lambdaRotatePerRadianSq \* angle \* angle \+[\s\S]*lambdaTranslatePerGameUnitSq \* translationSq' 'The solve must include the arrival-continuity regularizer: minimal correction from the seed pose onto the manifold, or the one-sided plateau lets the pose wander (validated: ident drift 19.1deg without it, 6.9deg with it).'
Require-Text $header 'runs? ONCE at grab' 'The header must state the solve is a one-shot at grab acquisition; it is not budgeted for per-frame use.'

# --- Fixture lockstep ----------------------------------------------------------

Require-Text 'tests/GrabPoseObjectiveTests.cpp' 'GrabPoseObjectiveFixtures\.h' 'The parity test must consume the generated fixtures; without them the header can drift from the offline harness the weights were fitted against.'
Require-Text 'tests/GrabPoseObjectiveFixtures.h' 'Generated by tools/generate_grab_pose_objective_fixtures\.py' 'Fixtures must declare their generator so they are regenerated, never hand-edited.'
Require-Text 'tools/generate_grab_pose_objective_fixtures.py' 'MAX_TRIS = 260' 'The fixture generator must subsample triangles exactly like the offline harness (MAX_TRIS=260) or goldens silently diverge from the fitted data.'

if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Host "FAIL: $_" }
    exit 1
}
Write-Host 'GrabPoseObjectiveSourceTests passed'
exit 0
