param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$failures = [System.Collections.Generic.List[string]]::new()

function Read-Source {
    param([string]$RelativePath)

    return Get-Content -Raw -LiteralPath (Join-Path $Root $RelativePath)
}

function Require-Text {
    param(
        [string]$RelativePath,
        [string]$Pattern,
        [string]$Message
    )

    $text = Read-Source $RelativePath
    if ($text -notmatch $Pattern) {
        $failures.Add("$RelativePath`: $Message")
    }
}

function Reject-Text {
    param(
        [string]$RelativePath,
        [string]$Pattern,
        [string]$Message
    )

    $text = Read-Source $RelativePath
    if ($text -match $Pattern) {
        $failures.Add("$RelativePath`: $Message")
    }
}

Require-Text 'tools/generate_grab_finger_calibration.py' 'workspace_root / "main_projects" / "hFRIK"' `
    'Offline grab-finger calibration must resolve hFRIK from the reorganized main-project tree.'
Reject-Text 'tools/generate_grab_finger_calibration.py' 'F4VR-CommonFramework' `
    'Offline grab-finger calibration must not depend on F4VR-CommonFramework sources.'
Reject-Text 'tools/generate_grab_finger_calibration.py' 'original frik deps' `
    'Offline grab-finger calibration must not reference the removed dependency tree.'
Require-Text 'tools/generate_grab_finger_calibration.py' 'runtime_landmark_reference_length' `
    'Offline reach scales must be normalized against the same root-flattened landmark length used by gameplay.'
Require-Text 'tools/generate_grab_finger_calibration.py' 'THUMB_LANES' `
    'Offline grab-finger calibration must bake explicit thumb wrap/opposition/side-pad lanes.'
Reject-Text 'tools/generate_grab_finger_calibration.py' 'path\.as_posix\(\)\.encode' `
    'Generated calibration source hashes must not depend on absolute workspace paths.'
Require-Text 'src/physics-interaction/grab/GeneratedGrabFingerCalibration.h' 'Generated by tools/generate_grab_finger_calibration.py' `
    'Baked grab-finger calibration data must be generated, not hand-authored.'
Require-Text 'src/physics-interaction/grab/GeneratedGrabFingerCalibration.h' 'kGrabFingerCalibrationSourceHash' `
    'Generated calibration data must record the source hash used for the bake.'
Require-Text 'src/physics-interaction/grab/GeneratedGrabFingerCalibration.h' 'BakedGrabThumbLane[\s\S]*Opposition[\s\S]*SidePad' `
    'Generated calibration data must include baked thumb opposition and side-pad lane metadata.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'kGrabFingerCalibrationSampleCount[\s\S]*kCalibratedFingerCurveSampleCount' `
    'Gameplay must assert that generated and runtime calibration sample counts match.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'makeBakedCalibratedFingerCurve' `
    'Gameplay grab finger solving must consume the baked calibration table.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'bakedGrabThumbProfile' `
    'Gameplay grab thumb solving must consume the baked thumb lane table.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'selectedThumbLaneLocalCorrectionStrength' `
    'Gameplay local thumb correction must use baked lane-specific correction strength.'
Require-Text 'src/physics-interaction/grab/GrabFinger.h' 'bakedCalibratedFingerMaxAngleRadians' `
    'Gameplay grab finger max curl angles must come from baked calibration data.'
Reject-Text 'src/physics-interaction/grab/GrabFinger.h' 'makeRuntimeCalibratedFingerCurve' `
    'Gameplay must not rebuild grab-finger calibration curves procedurally at runtime.'
Require-Text 'src/physics-interaction/hand/RootFlattenedFingerSkeletonRuntime.cpp' 'outSnapshot\.inPowerArmor = snapshot\.inPowerArmor' `
    'Baked calibration profile selection must use the same power-armor state as the root-flattened skeleton snapshot.'

$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) {
    $failures.Add('python: required to verify generated grab-finger calibration is up to date.')
} else {
    $generator = Join-Path $Root 'tools/generate_grab_finger_calibration.py'
    $output = & $python.Source $generator --check 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures.Add("tools/generate_grab_finger_calibration.py --check failed: $output")
    }
}

if ($failures.Count -gt 0) {
    $failures | ForEach-Object { Write-Error $_ }
    exit 1
}
