#pragma once

#include <string_view>

namespace rock::config
{
    struct DeveloperSettingMetadata
    {
        std::string_view section, key, category, description;
    };

    // UI help only. Types and defaults are obtained from the compiled loader.
    inline constexpr DeveloperSettingMetadata kDeveloperSettingMetadata[] = {
        { "PhysicsInteraction", "bDebugDrawGrabAuthorityProxy", "Developer 1. Debug Overlay: What To Draw", "Draws the hidden no-contact grab authority proxy target/axes used by ROCK dynamic grab." },
        { "PhysicsInteraction", "bDebugShowColliders", "Developer 1. Debug Overlay: What To Draw", "Master switch for all ROCK-owned collider visualizations below." },
        { "PhysicsInteraction", "bDebugShowTargetColliders", "Developer 1. Debug Overlay: What To Draw", "Draws the selected or held target body when the collider master is enabled." },
        { "PhysicsInteraction", "bDebugDrawColliderPhaseDiagnostics", "Developer 1. Debug Overlay: What To Draw", "Adds current-target, pre-step, post-solve, predicted-presentation shells, and their capture data when the collider master is enabled." },
        { "PhysicsInteraction", "bDebugShowHandAxes", "Developer 1. Debug Overlay: What To Draw", "Draws live transform axes. Red=X, green=Y, blue=Z." },
        { "PhysicsInteraction", "bDebugShowGrabPivots", "Developer 1. Debug Overlay: What To Draw", "Draws grab constraint pivots and the error line between hand-side and object-side pivots." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArc", "Developer 1. Debug Overlay: What To Draw", "NEW SWEPT-ARC FINGER SOLVER VISUALIZATION This is independent of bDebugShowGrabFingerProbes (the legacy straight/pad probe overlay). It reads the one-shot swept solve captured at grab time and never re-runs mesh queries. Pinch intentionally remains on its separate path. Cyan=Tip arc, green=Outer arc, purple=Inner arc, yellow=selected contact sphere, white=hit normal/live finger skeleton. Red/magenta/blue/orange mark miss fallback, close-limit hit, out-of-reach, and over-open respectively." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcText", "Developer 1. Debug Overlay: What To Draw", "Adds per-finger state/value/probe/lane labels and BVH work totals." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcLiveSkeleton", "Developer 1. Debug Overlay: What To Draw", "Draws the current rendered finger chains for direct comparison with the arcs." },
        { "PhysicsInteraction", "bDebugShowGrabFingerProbes", "Developer 1. Debug Overlay: What To Draw", "LEGACY ONLY: draws the former straight and pad probes. It is unrelated to the swept-arc visualization above." },
        { "PhysicsInteraction", "bDebugShowGrabPocketNormal", "Developer 1. Debug Overlay: What To Draw", "Draws the resolved mesh surface frame after a dynamic grab." },
        { "PhysicsInteraction", "bDebugDrawGrabContactPatch", "Developer 1. Debug Overlay: What To Draw", "Draws accepted contact-patch points used to fit the grab surface." },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorque", "Developer 1. Debug Overlay: What To Draw", "Draws a focused held-grab pivot force/lever view: target pivot, live pivot, correction vector, lever arm, and torque witness." },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorqueText", "Developer 1. Debug Overlay: What To Draw", "Adds a compact world label to the focused grab force/lever view." },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceCollider", "Developer 1. Debug Overlay: What To Draw", "Draws the hknp body/collider that owns the frozen object-side pivot B." },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceEvidence", "Developer 1. Debug Overlay: What To Draw", "Draws the mesh triangle/contact-patch evidence that produced the frozen pivot." },
        { "PhysicsInteraction", "bDebugDrawGrabSupportFrame", "Developer 1. Debug Overlay: What To Draw", "Draws the frozen grab support face frame at pivot B: normal, support axis, and binormal." },
        { "PhysicsInteraction", "bDebugDrawGrabPockets", "Developer 1. Debug Overlay: What To Draw", "Draws the live palm pocket and thumb/index pinch pocket for each hand." },
        { "PhysicsInteraction", "bDebugShowPalmVectors", "Developer 1. Debug Overlay: What To Draw", "Draws palm center plus close/far selection aim rays." },
        { "PhysicsInteraction", "bDebugDrawHandColliders", "Developer 1. Debug Overlay: What To Draw", "More specific overlay filters and draw limits." },
        { "PhysicsInteraction", "bDebugDrawHandBoneColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawBodyBoneColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawDynamicHandColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawHandBoneContacts", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxHandBoneBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxBodyBoneBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawWeaponColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawGrabbedWeaponPartCollider", "Developer 1. Debug Overlay: What To Draw", "Draws the exact current weapon-part collider selected by each active part grip." },
        { "PhysicsInteraction", "bDebugDrawNativeScopeActivation", "Developer 1. Debug Overlay: What To Draw", "Native-scope diagnosis: sight bounds, live camera, exact pre-activation target pose/aim/up guides, write readback, parent/local camera, and HMD guides." },
        { "PhysicsInteraction", "bDebugDrawAuthoredGripActivationZones", "Developer 1. Debug Overlay: What To Draw", "Visualizes the topology-specific authored cone/arc, live approach vector, and optional palm/fingertip collision witnesses. Witnesses are diagnostic only. Also draws the firing-grip reattach cylinders and live palm vectors during part carry." },
        { "PhysicsInteraction", "bDebugDrawWeaponAuthority", "Developer 1. Debug Overlay: What To Draw", "Draws two-handed weapon/hand/FRIK authority frames and mismatch evidence." },
        { "PhysicsInteraction", "bDebugGripFailureTelemetry", "Developer 1. Debug Overlay: What To Draw", "Enables the grip-failure telemetry ring (per-frame snapshots during manual ownership) and full incident dumps. Off: an incident logs one summary line." },
        { "PhysicsInteraction", "bDebugDrawLooseWeaponGripZones", "Developer 1. Debug Overlay: What To Draw", "Draws the loose-weapon projected grip point, palm relation, and equip radius state." },
        { "PhysicsInteraction", "bDebugDrawDynamicWeaponColliders", "Developer 1. Debug Overlay: What To Draw", "Draws the layer-51 dynamic weapon compound proxy and contact/correction telemetry." },
        { "PhysicsInteraction", "bDebugDumpWeaponAnimNodes", "Developer 1. Debug Overlay: What To Draw", "Logs first-person Weapon/WeaponLeft/AnimObject/Projectile anchors, transforms, child names, and subtree mesh counts. Useful for investigating equipped weapon mod swaps that expose geometry outside ROCK's current collision roots." },
        { "PhysicsInteraction", "iDebugMaxWeaponBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugWeaponAnimNodeDumpIntervalFrames", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCapturesPerFrame", "Developer 1. Debug Overlay: What To Draw", "Bounded overlay work and memory budgets. Zero disables the corresponding capture/upload/draw stream where noted. Ranges: captures 0..32, compound slots 1..1024, depth 1..8, queued/completed 0..256, uploads 0..16, cache entries 16..4096, cache bytes 1048576..536870912, body instances 0..171, line vertices 0..65536, text vertices 0..131072." },
        { "PhysicsInteraction", "iDebugMaxConvexSupportVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxCompoundChildren", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxCompoundDepth", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeQueuedJobs", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCompletedJobs", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeUploadsPerFrame", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCacheEntries", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCacheBytes", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxBodyInstances", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxLineVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxTextVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugUseBoundsForHeavyConvex", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugVerboseLogging", "Developer 2. Debug Logs, Telemetry, And Notifications", "Very noisy per-frame diagnostic logging. Use only while investigating a specific issue." },
        { "PhysicsInteraction", "bDebugGrabFrameLogging", "Developer 2. Debug Logs, Telemetry, And Notifications", "Focused logs for grab frame capture and held-object transform comparisons." },
        { "PhysicsInteraction", "bDebugVideoSyncMarker", "Developer 2. Debug Logs, Telemetry, And Notifications", "Optional video synchronization marker used only during diagnostics." },
        { "PhysicsInteraction", "fDebugVideoSyncMarkerSize", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabTimelineTrace", "Developer 2. Debug Logs, Telemetry, And Notifications", "Structured per-grab timeline rows for capture, constraint writes, solver response, and release. Use this when building graphs from ROCK.log. Very noisy when enabled." },
        { "PhysicsInteraction", "iDebugGrabTimelineTraceIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabAfterSolveAnomalySampling", "Developer 2. Debug Logs, Telemetry, And Notifications", "Sample after-solve proxy/body mismatch diagnostics without enabling full grab-frame logging. This reads live body and constraint atom state; keep disabled during normal gameplay." },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetry", "Developer 2. Debug Logs, Telemetry, And Notifications", "Timestamp-matched grab telemetry for comparing video, overlay text, and ROCK.log rows." },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryText", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryAxes", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryLogIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryTextMode", "Developer 2. Debug Logs, Telemetry, And Notifications", "0 = duplicate telemetry text into both VR eye halves. 1 = draw one text panel across the submitted texture." },
        { "PhysicsInteraction", "bDebugShowGrabNotifications", "Developer 2. Debug Logs, Telemetry, And Notifications", "In-game popup diagnostics for grab decisions." },
        { "PhysicsInteraction", "bDebugShowWeaponNotifications", "Developer 2. Debug Logs, Telemetry, And Notifications", "In-game popup diagnostics for weapon contact and support grip decisions." },
        { "PhysicsInteraction", "bDebugWeaponOmodDump", "Developer 2. Debug Logs, Telemetry, And Notifications", "One-shot research dump per equipped weapon build: installed OMOD records (attach point, model path), generated evidence bindings, and the assembled weapon node tree. Verbose; enable only when collecting part-identity data." },
        { "PhysicsInteraction", "bDebugHandTransformParity", "Developer 2. Debug Logs, Telemetry, And Notifications", "Compares ROCK's direct first-person skeleton hand transforms against the FRIK API path. Diagnostic only. It does not choose the active hand frame." },
        { "PhysicsInteraction", "bDebugHandWorldAuthority", "Developer 2. Debug Logs, Telemetry, And Notifications", "Periodic summary of the FRIK API v2 hand world authority: controller-hand reconstruction source counts and error probe, claim rebase publishes, and pre-FRIK scheduler state. Diagnostic only. Fallback and refusal warnings are always logged." },
        { "PhysicsInteraction", "bDebugWorldObjectOriginDiagnostics", "Developer 2. Debug Logs, Telemetry, And Notifications", "Logs and draws alternate world-origin candidates for selected or held objects. Diagnostic only. It does not change object motion." },
        { "PhysicsInteraction", "iDebugWorldObjectOriginLogIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "fDebugWorldObjectOriginMismatchWarnGameUnits", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugShowRootFlattenedFingerSkeletonMarkers", "Developer 3. Skeleton Debug", "Draws markers and axes for live first-person skeleton bones." },
        { "PhysicsInteraction", "bDebugShowSkeletonBoneVisualizer", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugSkeletonBoneMode", "Developer 3. Skeleton Debug", "0 = minimal/core bones, 1 = core body and fingers, higher modes may draw more if supported." },
        { "PhysicsInteraction", "iDebugSkeletonBoneSource", "Developer 3. Skeleton Debug", "Selects the skeleton source used by the debug visualizer." },
        { "PhysicsInteraction", "iDebugMaxSkeletonBonesDrawn", "Developer 3. Skeleton Debug", "Draw limits and filters for skeleton debug drawing." },
        { "PhysicsInteraction", "bDebugDrawSkeletonBoneAxes", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugMaxSkeletonBoneAxesDrawn", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "sDebugSkeletonAxisBoneFilter", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "bDebugLogSkeletonBones", "Developer 3. Skeleton Debug", "Logs bone names and truncation information to ROCK.log." },
        { "PhysicsInteraction", "bDebugLogSkeletonBoneTruncation", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugSkeletonBoneLogIntervalFrames", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "sDebugSkeletonBoneLogFilter", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "fDebugRootFlattenedFingerSkeletonMarkerSize", "Developer 3. Skeleton Debug", "Marker and axis sizes for skeleton debug visuals." },
        { "PhysicsInteraction", "fDebugSkeletonBonePointSize", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "fDebugSkeletonBoneAxisLength", "Developer 3. Skeleton Debug", "" },
        { "Debug", "bDeveloperModeEnabled", "Debug", "Gates advanced/tuning-only features not meant for normal play. Currently: pressing A while holding an object records/overwrites a saved grab offset for that object+hand. Saved offsets keep applying on future grabs regardless of this setting - it only gates recording new ones." },
        { "Debug", "sLogPattern", "Debug", "Text format for each ROCK.log line." },
        { "Debug", "iLogSampleMilliseconds", "Debug", "Minimum time between repeated sampled diagnostic messages." },
        { "Debug", "bPerformanceProfilerEnabled", "Debug", "Async Performance Profiler Independent from iLogLevel. When enabled, timing scopes stay on the frame path, but completed profiler windows are queued to a bounded background writer. Output goes to ROCK_Profiler.log, not ROCK.log. File formatting/writes are not done by grab, reload, physics, or frame update code. If the writer falls behind, profiler windows are dropped instead of stalling gameplay." },
        { "Debug", "iPerformanceProfilerLogIntervalFrames", "Debug", "Number of frames per queued profiler window after warmup. Larger values reduce file traffic." },
        { "Debug", "iPerformanceProfilerWarmupFrames", "Debug", "Startup/reload frames ignored before profiler windows are emitted." },
        { "Debug", "bPerformanceProfilerOverlayText", "Debug", "Draws latest profiler window as in-game overlay text. Leave false for clean file-only profiling." },
    };
}
