#pragma once

#include <string_view>

namespace rock::config
{
    struct DeveloperSettingMetadata
    {
        std::string_view section, key, category, description;
    };

    // Developer ownership and UI help. Types and defaults come from the compiled loader.
    inline constexpr DeveloperSettingMetadata kDeveloperSettingMetadata[] = {
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceX", "3. Palm And Pointing Directions", "Legacy authored palm pivot used by API palm position, telemetry, debug tuning, two-handed grip, and non-dynamic helpers. Dynamic object grabs use the generated hidden proxy authority pivot below." },
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceY", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceZ", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceX", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceY", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceZ", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetXGameUnits", "3. Palm And Pointing Directions", "Local offset for the hidden grab authority proxy/seat point, in corrected palm proxy space. X follows the fingers, -Y moves into the palm face/skin, +Y moves to the back of the hand, and Z moves across the palm. This does not move the real palm/finger physics colliders." },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetYGameUnits", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetZGameUnits", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetXGameUnits", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetYGameUnits", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetZGameUnits", "3. Palm And Pointing Directions", "" },
        { "PhysicsInteraction", "bWeaponCollisionBlocksProjectiles", "4. Weapon Collision And Support Grip", "Controls whether ROCK weapon hulls collide with projectile/spell layers. False avoids self-collisions with modded projectile systems while aiming." },
        { "PhysicsInteraction", "bWeaponCollisionBlocksSpells", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "bWeaponCollisionPreserveGaps", "4. Weapon Collision And Support Grip", "False: original convex fitting. True: bounded gap-preserving compounds. Changing this key rebuilds weapon colliders after live INI reload. Compare with bPerformanceProfilerEnabled: weaponColliderBuild/Create vs weaponGapColliderBuild/Create." },
        { "PhysicsInteraction", "fWeaponCollisionVisualStabilizationSeconds", "4. Weapon Collision And Support Grip", "Seconds ROCK waits for the visual weapon tree to stay visible/stable before replacing generated hulls after weapon/mod swaps." },
        { "PhysicsInteraction", "fWeaponCollisionMaxLinearVelocity", "4. Weapon Collision And Support Grip", "Maximum speed allowed when ROCK keyframes generated weapon hulls." },
        { "PhysicsInteraction", "fWeaponCollisionMaxAngularVelocity", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "fWeaponCollisionGripRecoveryDistanceGameUnits", "4. Weapon Collision And Support Grip", "Immediately resets a failed dynamic weapon collider onto the firing hand if its live firing-grip authority point is farther away than this distance. This catastrophic-failure limit is separate from normal wall-contact convergence. 210 game units is about 3 metres. Game units (~1.4cm each)." },
        { "PhysicsInteraction", "fWeaponInteractionTouchRadius", "4. Weapon Collision And Support Grip", "Small sphere around each configured legacy palm pivot. If it overlaps a generated weapon collider, the grab uses ROCK's unrestricted dynamic seat." },
        { "PhysicsInteraction", "fWeaponInteractionProbeRadius", "4. Weapon Collision And Support Grip", "Broader per-hand search used when the palm is not touching the weapon. With authored weapon grips enabled, a grab acquired only by this probe uses the modeler's authored firing/support seat instead of the dynamic mesh seat." },
        { "PhysicsInteraction", "fFiringGripProximitySupportRadius", "4. Weapon Collision And Support Grip", "Every support grab inside this distance from the firing grip stays visual-only so pistols retain a stable support pose without competing weapon authority. ROCK always owns this behavior. An active equipped-weapon addon may override only the radius through the ROCK V1 API. Game units (~1.4cm each)." },
        { "PhysicsInteraction", "bWeaponSupportGripHandLerpEnabled", "4. Weapon Collision And Support Grip", "Eases ROCK's external FRIK hand target into an equipped weapon support grip. This is visual-only: weapon aim authority remains immediate." },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpTimeMin", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpTimeMax", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpMinDistance", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpMaxDistance", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "bWeaponSupportSurfaceSeatEnabled", "4. Weapon Collision And Support Grip", "Seats the visual support palm toward the contacted surface without rotating the weapon." },
        { "PhysicsInteraction", "fWeaponSupportSurfaceSeatMaxDegrees", "4. Weapon Collision And Support Grip", "" },
        { "PhysicsInteraction", "bBodyBoneCollidersEnabled", "8. Hand And Body Collision From Skeleton Bones", "Creates generated keyframed colliders for the torso, arms, legs, and feet. False disables the entire body set while leaving hand and finger colliders alive." },
        { "PhysicsInteraction", "bBodyBoneLegAndFootCollidersEnabled", "8. Hand And Body Collision From Skeleton Bones", "Adds leg and foot colliders to the generated body set. False keeps torso and arm colliders while omitting every leg and foot body." },
        { "PhysicsInteraction", "fBodyBoneColliderStandardRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "Global generated body collider size scales. Power armor starts from a separate larger descriptor set, then applies these scales." },
        { "PhysicsInteraction", "fBodyBoneColliderStandardLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderStandardConvexRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorConvexRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderTorsoRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "Role-specific scales applied after the standard/power-armor profile scale." },
        { "PhysicsInteraction", "fBodyBoneColliderArmRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderLegRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderFootRadiusScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderTorsoLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderArmLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderLegLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "fBodyBoneColliderFootLengthScale", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "sBodyBoneColliderZoneScaleOverrides", "8. Hand And Body Collision From Skeleton Bones", "Optional descriptor-specific size overrides for tuning stash/holster/backpack zones. Format: Zone=radius,length,convex;PowerArmor.Zone=radius,length,convex Zone names: Pelvis, SpineLower, SpineUpper, Chest, NeckHead, LeftShoulder, LeftUpperArm, LeftForearmUpper, LeftForearmLower, LeftHand, RightShoulder, RightUpperArm, RightForearmUpper, RightForearmLower, RightHand, LeftHip, LeftThigh, LeftCalf, LeftFoot, RightHip, RightThigh, RightCalf, RightFoot." },
        { "PhysicsInteraction", "sBodyBoneColliderRadiusScaleOverrides", "8. Hand And Body Collision From Skeleton Bones", "Optional individual generated body collider radius scale overrides. Format: Zone=radiusScale;StartBone>EndBone=radiusScale;PowerArmor.Zone=radiusScale;PowerArmor.StartBone>EndBone=radiusScale Examples: LeftForearmLower=0.85;RArm_ForeArm2>RArm_ForeArm3=0.90;PowerArmor.Chest=1.10" },
        { "PhysicsInteraction", "bHandCollisionStaticWorldEnabled", "8. Hand And Body Collision From Skeleton Bones", "Allows generated hand colliders to collide with static/animstatic world geometry for native contact evidence." },
        { "PhysicsInteraction", "bGlobalSurfaceGrabEnabled", "8. Hand And Body Collision From Skeleton Bones", "Makes dynamic-hand world-surface contacts eligible for fixed-anchor grab fallback." },
        { "PhysicsInteraction", "bSurfaceMeshGrabEnabled", "8. Hand And Body Collision From Skeleton Bones", "Uses the contacted render mesh as the spatial authority for fixed-surface grabs." },
        { "PhysicsInteraction", "fSurfaceMeshGrabMaxProjectionDistanceGameUnits", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "iSurfaceMeshGrabMaxTriangles", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "sHandBoneColliderRadiusScaleOverrides", "8. Hand And Body Collision From Skeleton Bones", "Optional generated hand capsule-like collider radius scale overrides. Palm-box roles are controlled by X/Y/Z below. Role names: ThumbBase, ThumbMiddle, ThumbTip, IndexBase, IndexMiddle, IndexTip, MiddleBase, MiddleMiddle, MiddleTip, RingBase, RingMiddle, RingTip, PinkyBase, PinkyMiddle, PinkyTip. Format: Role=radiusScale;PowerArmor.Role=radiusScale" },
        { "PhysicsInteraction", "sHandPalmColliderDimensionScaleOverrides", "8. Hand And Body Collision From Skeleton Bones", "Optional generated palm-box collider local dimension scale overrides. Local X=fingers/segment length, local Y=palm depth, local Z=cross-palm width. Role names: PalmAnchor, PalmFace, PalmBack, PalmHeel, ThumbPad. Format: Role=xScale,yScale,zScale;PowerArmor.Role=xScale,yScale,zScale" },
        { "PhysicsInteraction", "bHandBoneCollidersRequirePalmAnchor", "8. Hand And Body Collision From Skeleton Bones", "Requires the palm anchor before creating hand bone colliders." },
        { "PhysicsInteraction", "fHandBoneColliderMaxLinearVelocity", "8. Hand And Body Collision From Skeleton Bones", "Speed clamps for bone-driven hand colliders." },
        { "PhysicsInteraction", "fHandBoneColliderMaxAngularVelocity", "8. Hand And Body Collision From Skeleton Bones", "" },
        { "PhysicsInteraction", "bPullToObjectCenterEnabled", "9. Object Selection, Pulling, And Push Assist", "Far grabs pull the object's CENTER to the hand instead of the ray-hit point (a hit at selection range is aim noise, not grip intent). The arrival seat then settles the surface onto the palm via the seat machinery." },
        { "PhysicsInteraction", "bPullLongAxisPresentationEnabled", "9. Object Selection, Pulling, And Push Assist", "Long-object presentation during pull flight: rotates elongated props (brooms, bottles) so their mesh long axis lines up with the hand's thumb->pinky line before arrival. Flight-only; held objects are never rotated. Elongation is the RMS extent ratio between the mesh's dominant and second axis (compact objects ~1 skip presentation). Gain is proportional rad/s per rad of error." },
        { "PhysicsInteraction", "fPullPresentationMinElongationRatio", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fPullPresentationAngularGainPerSecond", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fPullPresentationMaxAngularSpeedRadiansPerSecond", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fPullPresentationGripAxisTiltDegrees", "9. Object Selection, Pulling, And Push Assist", "Tilts the presentation target off pure cross-palm Z toward fingers-forward +X, in degrees (0..45): the thumb occupies the pure-Z line, so the natural long-object hold sits a few degrees toward the fingertips. Applies to both the pull-flight servo and the force-grab seat alignment. This is an anatomical magnitude, not a signed rotation. Authored Z reverses its cross-palm direction between hands, but +X points toward the fingertips on both. ROCK resolves the live axes first, then tilts each signed Z axis toward its own +X, so one value has the same meaning for both hands." },
        { "PhysicsInteraction", "bForceGrabSeatAlignmentEnabled", "9. Object Selection, Pulling, And Push Assist", "Applies long-axis presentation alignment to force-grab arrival seats." },
        { "PhysicsInteraction", "bGrabSeatRollAlignmentEnabled", "9. Object Selection, Pulling, And Push Assist", "Applies face-to-palm roll alignment to programmatic arrival seats." },
        { "PhysicsInteraction", "fGrabSeatRollMinSecondElongationRatio", "9. Object Selection, Pulling, And Push Assist", "Shape-classification gate shared by the flight presentation servo and the grab pose solver: sqrt(lambda2/lambda3) of the mesh PCA at or above this ratio marks a distinct flat face (plate class). The solver uses the class for its rod-only terms; plates keep their edge/corner holds (31 verified plate holds put the face normal 63 deg off the palm normal - edge holds are the intended grip, not an artifact)." },
        { "PhysicsInteraction", "iObjectPhysicsTreeMaxDepth", "9. Object Selection, Pulling, And Push Assist", "Maximum scene-node depth used when scanning an object for physics bodies." },
        { "PhysicsInteraction", "bDynamicPushAssistEnabled", "9. Object Selection, Pulling, And Push Assist", "Lets moving hands or weapon hulls nudge already-dynamic props. It never converts static or keyframed objects into dynamic objects." },
        { "PhysicsInteraction", "fDynamicPushMinSpeed", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fDynamicPushMaxImpulse", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fDynamicPushCooldownSeconds", "9. Object Selection, Pulling, And Push Assist", "" },
        { "PhysicsInteraction", "fGrabLinearTau", "10. Grab Drive Feel", "Linear shared-constraint motor response. Lower tau is stiffer and faster. Higher damping calms oscillation." },
        { "PhysicsInteraction", "fGrabLinearDamping", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLinearProportionalRecovery", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLinearConstantRecovery", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabAngularTau", "10. Grab Drive Feel", "Angular shared-constraint motor response. Same idea as linear motor, but for rotation." },
        { "PhysicsInteraction", "fGrabAngularDamping", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabAngularProportionalRecovery", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabAngularConstantRecovery", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabConstraintMaxForce", "10. Grab Drive Feel", "Maximum force the grab constraint can apply." },
        { "PhysicsInteraction", "bGrabEffectiveMotorMassFloorEnabled", "10. Grab Drive Feel", "Keeps the motor's effective mass finite for very light or unstable bodies." },
        { "PhysicsInteraction", "fGrabEffectiveMotorMassFloor", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "bGrabPhysicsRateForceScalingEnabled", "10. Grab Drive Feel", "Controlled locomotion-stutter A/B (2026-08-22): keep the ordinary-object motor at the configured 2000 force on every Havok substep. The prior default multiplied force by sqrt(90 / physicsHz), producing about 1643-2245 force as FO4VR alternated between 7.5 ms and 14 ms substeps. Remove this test override after the constant-force result is decided." },
        { "PhysicsInteraction", "fGrabPhysicsRateReferenceHz", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabPhysicsRateForceScaleExponent", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabPhysicsRateMinForceScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabPhysicsRateMaxForceScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabMaxForceToMassRatio", "10. Grab Drive Feel", "Caps force by object mass so light objects do not explode out of the hand." },
        { "PhysicsInteraction", "fForceGrabAttachSettleSeconds", "10. Grab Drive Feel", "Waits for a stable live hand transform before a force grab freezes its relation." },
        { "PhysicsInteraction", "fGrabForceFadeInTime", "10. Grab Drive Feel", "Time for grab force to ramp in after pickup." },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearTauMultiplier", "10. Grab Drive Feel", "Multipliers for non-equipped weapon refs grabbed as loose dynamic objects. Loose weapons keep the same mass cap as generic objects, but get the a higher base force before that cap is applied. Angular force is separate so long multipart weapons can rotate without increasing linear pull." },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularTauMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintCollisionTauMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearDampingMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularDampingMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintMaxForceMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularForceMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearRecoveryMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularRecoveryMultiplier", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabTauMin", "10. Grab Drive Feel", "Contact-softened tau. Normal held linear/angular tau stay fixed at their base values." },
        { "PhysicsInteraction", "fGrabTauLerpSpeed", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "bGrabLongObjectAngularScalingEnabled", "10. Grab Drive Feel", "Reduces held angular speed for long objects by grip-to-extents lever length. This keeps long guns/objects from sweeping as if their far end had no leverage." },
        { "PhysicsInteraction", "fGrabLongObjectReferenceLeverGameUnits", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLongObjectMinAngularScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "bGrabPivotQualityAngularScalingEnabled", "10. Grab Drive Feel", "Limits release angular velocity when the grab pivot has weak normal/contact support." },
        { "PhysicsInteraction", "fGrabPositionOnlyAngularScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabSmallObjectReferenceLeverGameUnits", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabSmallObjectAngularScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabLowContactSupportAngularScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabMinAngularAuthorityScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabWeakPivotTwistScale", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabMaxInertiaRatio", "10. Grab Drive Feel", "Clamps extreme inertia tensors on grabbed rigid bodies to keep the solver stable." },
        { "PhysicsInteraction", "fGrabMinInertia", "10. Grab Drive Feel", "" },
        { "PhysicsInteraction", "fGrabMaxDeviation", "11. Grab Safety, Release, And Player Movement", "Force-releases if the held object stays too far from the palm for too long." },
        { "PhysicsInteraction", "fGrabMaxDeviationTime", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fThrowVelocityMultiplier", "11. Grab Safety, Release, And Player Movement", "Multiplies held-object velocity when you release to throw." },
        { "PhysicsInteraction", "bGrabControllerDerivedThrowVelocityEnabled", "11. Grab Safety, Release, And Player Movement", "Uses tracked hand velocity, COM-relative angular swing, and a small object-velocity blend for throws." },
        { "PhysicsInteraction", "fGrabThrowObjectVelocityBlend", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabThrowTangentialVelocityScale", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabThrowMaxVelocityHavok", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabThrowAngularVelocityScale", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabThrowMaxAngularVelocityRadiansPerSecond", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabReleaseHandCollisionDelaySeconds", "11. Grab Safety, Release, And Player Movement", "Keeps hand collision suppressed briefly after release so the object is not launched instantly." },
        { "PhysicsInteraction", "bShoulderStashEnabled", "11. Grab Safety, Release, And Player Movement", "Shoulder stash transfers a held loose item to inventory when grip is released inside the HMD-relative back volume. Generated FRIK body-zone colliders are backup evidence for tracking loss and remain the preferred path for holsters." },
        { "PhysicsInteraction", "bEquippedWeaponShoulderStashEnabled", "11. Grab Safety, Release, And Player Movement", "Equipped weapons use the same HMD-relative back volumes and remain equipped. Toggle-grab: press inside to sheath or retrieve; release only rearms. Hold-to-grab: hold inside and release to sheath; press inside to retrieve, then pull forward or release while the weapon remains drawn." },
        { "PhysicsInteraction", "bShoulderStashUseBodyZoneColliders", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "bShoulderStashUseHmdBackVolume", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashEnterPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashExitPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashMinDwellSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashMaxSpeedGameUnitsPerSecond", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashRecentContactSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashSustainedContactMissSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetXGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetYGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetZGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetXGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetYGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetZGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackRadiusGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackEnterPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackExitPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fShoulderStashHmdBackMinBehindGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "bShoulderStashShowCollectedNotifications", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "bMouthConsumeEnabled", "11. Grab Safety, Release, And Player Movement", "Mouth consume uses a tight HMD-relative sphere near the mouth. Only loose ALCH ingestibles can become mouth candidates; other objects use backpack stash/drop paths." },
        { "PhysicsInteraction", "bMouthConsumeAllowPoison", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetXGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetYGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetZGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeRadiusGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeEnterPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeExitPaddingGameUnits", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeMinDwellSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fMouthConsumeMaxSpeedGameUnitsPerSecond", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "bGrabNearbyDampingEnabled", "11. Grab Safety, Release, And Player Movement", "Temporarily calms nearby dynamic clutter when a grab starts. Uses verified FO4VR hknp motion-property damping leases with safe restore. Damping values are hknp per-second coefficients, not normalized percentages." },
        { "PhysicsInteraction", "fGrabNearbyDampingRadius", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabNearbyDampingSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabNearbyLinearDamping", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabNearbyAngularDamping", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "bGrabHeldMassMovementSlowdownEnabled", "11. Grab Safety, Release, And Player Movement", "Reduces player movement speed while carrying held mass." },
        { "PhysicsInteraction", "fGrabHeldMassMovementMassProportion", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabHeldMassMovementMassExponent", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabHeldMassMovementMaxReduction", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabHeldMassMovementFadeOutSeconds", "11. Grab Safety, Release, And Player Movement", "" },
        { "PhysicsInteraction", "fGrabTouchAcquireDistanceGameUnits", "12. Hand-Pocket Grab Acquisition", "Distance from the hand pocket where an object is considered already touching." },
        { "PhysicsInteraction", "fGrabNearConvergeDistanceGameUnits", "12. Hand-Pocket Grab Acquisition", "Distance where the object should converge into the palm pocket instead of finalizing immediately." },
        { "PhysicsInteraction", "fGrabPocketDepthGameUnits", "12. Hand-Pocket Grab Acquisition", "Hand-pocket offset and radius, in game units, from the root-flattened palm frame." },
        { "PhysicsInteraction", "fGrabPocketRadiusGameUnits", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabSeatDepthMaxGameUnits", "12. Hand-Pocket Grab Acquisition", "Legacy seat-depth stop and penetration backstop dimensions, in game units." },
        { "PhysicsInteraction", "fGrabSeatDepthFootprintRadiusGameUnits", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabSeatPenetrationBackstopFootprintRadiusGameUnits", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabSeatDepthSkinGameUnits", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabGripInsetGameUnits", "12. Hand-Pocket Grab Acquisition", "Moves the captured grip point slightly inside the object from the raw hit/mesh seed." },
        { "PhysicsInteraction", "fGrabConvergeMaxTimeSeconds", "12. Hand-Pocket Grab Acquisition", "Optional near-converge diagnostic timeout. A value of 0 disables timeout promotion." },
        { "PhysicsInteraction", "fGrabConvergeStableSeconds", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabConvergeMaxSeparatingSpeedGameUnitsPerSecond", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "fGrabAcquisitionVisualStartDistanceGameUnits", "12. Hand-Pocket Grab Acquisition", "" },
        { "PhysicsInteraction", "bGrabMultiFingerContactValidationEnabled", "13. Grab Contact Evidence", "Requires grouped finger contact evidence before trusting a mesh grab." },
        { "PhysicsInteraction", "iGrabContactQualityMode", "13. Grab Contact Evidence", "0 = permissive, 1 = hybrid patch and finger evidence, 2 = strict grouped-finger debug." },
        { "PhysicsInteraction", "iGrabMinFingerContactGroups", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabMinFingerContactSpreadGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabFingerContactMeshSnapMaxDistanceGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabSurfaceBehindPalmToleranceGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabOppositionContactMaxAgeSeconds", "13. Grab Contact Evidence", "Maximum age in seconds for semantic contacts used as touch evidence." },
        { "PhysicsInteraction", "bGrabPinchPocketEnabled", "13. Grab Contact Evidence", "Small-object pinch pocket. Chosen only at close-grab commit, then frozen for the hold." },
        { "PhysicsInteraction", "bGrabPinchCloseSelectionEnabled", "13. Grab Contact Evidence", "Allows a fallback close-selection cast along the pinch direction when the palm close cast misses." },
        { "PhysicsInteraction", "fGrabPinchCompactMaxExtentGameUnits", "13. Grab Contact Evidence", "Compact classification also requires the object's THINNEST extent to fit the ThinRodMaxCrossSection value below - mugs/cans are compact by size but too thick to pinch, so they fall through to the palm grab machinery." },
        { "PhysicsInteraction", "fGrabPinchThinRodMaxLengthGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchThinRodMaxCrossSectionGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchMaxPocketDistanceGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchMinFingerGapGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchMaxFingerGapGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchThumbIndexMaxOpenValue", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchOtherFingerCurlValue", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchSurfaceInsetGameUnits", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceX", "13. Grab Contact Evidence", "Pinch detection direction is authored in ROCK hand space: X=fingers, Y=palm depth, Z=signed cross-palm." },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceY", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceZ", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabPinchDetectionAxisBlend", "13. Grab Contact Evidence", "Blends the live thumb-index axis with the authored pinch direction for mesh surface search." },
        { "PhysicsInteraction", "bGrabHandLerpEnabled", "13. Grab Contact Evidence", "Moves the rendered hand toward the mesh-matched held pose during grab startup." },
        { "PhysicsInteraction", "fGrabHandLerpTimeMin", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandLerpTimeMax", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandLerpMinDistance", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandLerpMaxDistance", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "bGrabHandReturnEnabled", "13. Grab Contact Evidence", "Smooths the rendered hand back to live tracking after releasing a grabbed object." },
        { "PhysicsInteraction", "fGrabHandReturnTimeMin", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandReturnTimeMax", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandReturnMinDistance", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandReturnMaxDistance", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandReturnMinAngleDegrees", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "fGrabHandReturnMaxAngleDegrees", "13. Grab Contact Evidence", "" },
        { "PhysicsInteraction", "bGrabMeshFingerPoseEnabled", "14. Finger Pose", "Computes custom finger curl from the held object's visible mesh." },
        { "PhysicsInteraction", "bGrabMeshJointPoseEnabled", "14. Finger Pose", "Sends per-joint finger values to FRIK when available instead of one curl per finger." },
        { "PhysicsInteraction", "fGrabFingerMinValue", "14. Finger Pose", "Lowest allowed finger value. 0=fully closed, 1=fully straight." },
        { "PhysicsInteraction", "fGrabFingerPoseSmoothingSpeed", "14. Finger Pose", "Maximum per-second finger pose movement." },
        { "PhysicsInteraction", "bGrabMeshLocalTransformPoseEnabled", "14. Finger Pose", "Uses FRIK's authored finger joint transforms plus bounded mesh-contact aim correction." },
        { "PhysicsInteraction", "fGrabFingerLocalTransformSmoothingSpeed", "14. Finger Pose", "" },
        { "PhysicsInteraction", "fGrabFingerLocalTransformMaxCorrectionDegrees", "14. Finger Pose", "" },
        { "PhysicsInteraction", "fGrabFingerSurfaceAimStrength", "14. Finger Pose", "" },
        { "PhysicsInteraction", "bGrabFingerRejectBacksideHits", "14. Finger Pose", "" },
        { "PhysicsInteraction", "fGrabFingerSurfacePlaneToleranceGameUnits", "14. Finger Pose", "" },
        { "PhysicsInteraction", "fGrabFingerSweepContactRadiusGameUnits", "14. Finger Pose", "Swept-arc finger solver: finger-pad contact sphere radius. Bigger = fingers stop earlier (hover), smaller = deeper wrap before contact. Finger-pad contact radius for the swept-arc solver (0.05-4). The old finger-width air gap was a solver bug (fixed: chord de-rotation), NOT this radius - values near 0 now make fingers clip into the mesh." },
        { "PhysicsInteraction", "fGrabFingerSweepMaxOpenValue", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "fGrabThumbSweepMaxOpenValue", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "fGrabThumbOppositionStrength", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "fGrabThumbAlternateCurveStrength", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "bGrabThumbSurfaceSafetyEnabled", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "fGrabThumbSurfaceSafetyMarginGameUnits", "1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", "" },
        { "PhysicsInteraction", "fGrabLateralWeight", "15. Mesh Contact And Grab Evidence", "Weighting used when choosing the best mesh triangle for grab contact." },
        { "PhysicsInteraction", "fGrabDirectionalWeight", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabMaxTriangleDistance", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "bGrabMeshContactOnly", "15. Mesh Contact And Grab Evidence", "Uses visual mesh as the contact source. Collision still identifies the object body." },
        { "PhysicsInteraction", "bGrabRequireMeshContact", "15. Mesh Contact And Grab Evidence", "Fails generic close grab when no mesh contact is found. Authored ROCK grab nodes still work." },
        { "PhysicsInteraction", "bGrabContactPatchEnabled", "15. Mesh Contact And Grab Evidence", "Palm-plane probe patch used to capture the touched object-local point." },
        { "PhysicsInteraction", "iGrabContactPatchProbeCount", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabContactPatchProbeSpacingGameUnits", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabContactPatchProbeRadiusGameUnits", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabContactPatchMeshSnapMaxDistanceGameUnits", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabContactPatchMaxNormalAngleDegrees", "15. Mesh Contact And Grab Evidence", "" },
        { "PhysicsInteraction", "fGrabAlignmentMaxSelectionToMeshDistance", "15. Mesh Contact And Grab Evidence", "Mesh-snap gate used by contact-patch evidence." },
        { "PhysicsInteraction", "bSelectedCloseFingerCurlEnabled", "16. Close-Hand Curl", "Pre-curls the hand when close selection is active." },
        { "PhysicsInteraction", "fSelectedCloseFingerAnimMaxHandSpeed", "16. Close-Hand Curl", "" },
        { "PhysicsInteraction", "fSelectedCloseFingerAnimValue", "16. Close-Hand Curl", "" },
        { "PhysicsInteraction", "bGrabHapticsEnabled", "17. Grab And Held-Object Haptics", "Pulses for grab commit, pull start/catch, and held-object impacts." },
        { "PhysicsInteraction", "fGrabHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fGrabHapticBaseIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fGrabHapticMaxIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fGrabHapticMassScale", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fGrabHapticMassExponent", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fPullStartHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fPullCatchHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fSelectionLockHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fSelectionLockReleaseHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fSelectionLockReleaseHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "bSurfaceGrabHapticsEnabled", "17. Grab And Held-Object Haptics", "Fixed-surface grabs use a longer confirmation pulse." },
        { "PhysicsInteraction", "fSurfaceGrabHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fSurfaceGrabHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "bHeldImpactHapticsEnabled", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticBaseIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticMaxIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticSpeedScale", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticMassScale", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticMassExponent", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticMinSpeedGameUnits", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticCooldownSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fHeldImpactHapticDampedMultiplier", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "bShoulderStashHapticsEnabled", "17. Grab And Held-Object Haptics", "Shoulder stash haptics pulse clearly while an item is inside the stash zone, then fire a stronger confirmation on transfer." },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticBaseIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticIntervalSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fShoulderStashCommitHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fShoulderStashCommitHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "bMouthConsumeHapticsEnabled", "17. Grab And Held-Object Haptics", "Mouth consume haptics pulse while a consumable is in the mouth zone, then fire a confirmation on consume." },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticBaseIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticIntervalSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fMouthConsumeCommitHapticDurationSeconds", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "fMouthConsumeCommitHapticIntensity", "17. Grab And Held-Object Haptics", "" },
        { "PhysicsInteraction", "bDebugDrawGrabAuthorityProxy", "Developer 1. Debug Overlay: What To Draw", "Draws the hidden no-contact grab authority proxy target/axes used by ROCK dynamic grab." },
        { "PhysicsInteraction", "bDebugShowColliders", "Developer 1. Debug Overlay: What To Draw", "Master switch for all ROCK-owned collider visualizations below." },
        { "PhysicsInteraction", "bDebugShowTargetColliders", "Developer 1. Debug Overlay: What To Draw", "Draws the selected or held target body when the collider master is enabled." },
        { "PhysicsInteraction", "bDebugDrawColliderPhaseDiagnostics", "Developer 1. Debug Overlay: What To Draw", "Adds current-target, pre-step, post-solve, predicted-presentation shells, and their capture data when the collider master is enabled." },
        { "PhysicsInteraction", "bDebugShowHandAxes", "Developer 1. Debug Overlay: What To Draw", "Draws live transform axes. Red=X, green=Y, blue=Z." },
        { "PhysicsInteraction", "bDebugShowGrabPivots", "Developer 1. Debug Overlay: What To Draw", "Draws grab constraint pivots and the error line between hand-side and object-side pivots." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArc", "Developer 1. Debug Overlay: What To Draw", "NEW SWEPT-ARC FINGER SOLVER VISUALIZATION This is independent of bDebugShowGrabFingerProbes (the legacy straight/pad probe overlay). It reads the one-shot swept solve captured at grab time and never re-runs mesh queries. Pinch intentionally remains on its separate path. Cyan=Tip arc, green=Outer arc, purple=Inner arc, yellow=selected contact sphere, white=hit normal/live finger skeleton. Red/magenta/blue/orange mark miss fallback, close-limit hit, out-of-reach, and over-open respectively." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcText", "Developer 1. Debug Overlay: What To Draw", "Adds per-finger state/value/probe/lane labels and BVH work totals." },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcLiveSkeleton", "Developer 1. Debug Overlay: What To Draw", "Draws the current rendered finger chains for direct comparison with the arcs." },
        { "PhysicsInteraction", "bDebugShowGrabFingerProbes", "Developer 1. Debug Overlay: What To Draw", "LEGACY ONLY: draws the former straight and pad probes. It is unrelated to the swept-arc visualization above." },
        { "PhysicsInteraction", "bDebugShowGrabPocketNormal", "Developer 1. Debug Overlay: What To Draw", "Draws the resolved mesh surface frame after a dynamic grab." },
        { "PhysicsInteraction", "bDebugDrawGrabContactPatch", "Developer 1. Debug Overlay: What To Draw", "Draws accepted contact-patch points used to fit the grab surface." },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorque", "Developer 1. Debug Overlay: What To Draw", "Draws a focused held-grab pivot force/lever view: target pivot, live pivot, correction vector, lever arm, and torque witness." },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorqueText", "Developer 1. Debug Overlay: What To Draw", "Adds a compact world label to the focused grab force/lever view." },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceCollider", "Developer 1. Debug Overlay: What To Draw", "Draws the hknp body/collider that owns the frozen object-side pivot B." },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceEvidence", "Developer 1. Debug Overlay: What To Draw", "Draws the mesh triangle/contact-patch evidence that produced the frozen pivot." },
        { "PhysicsInteraction", "bDebugDrawGrabSupportFrame", "Developer 1. Debug Overlay: What To Draw", "Draws the frozen grab support face frame at pivot B: normal, support axis, and binormal." },
        { "PhysicsInteraction", "bDebugDrawGrabPockets", "Developer 1. Debug Overlay: What To Draw", "Draws the live palm pocket and thumb/index pinch pocket for each hand." },
        { "PhysicsInteraction", "bDebugShowPalmVectors", "Developer 1. Debug Overlay: What To Draw", "Draws palm center plus close/far selection aim rays." },
        { "PhysicsInteraction", "bDebugDrawHandColliders", "Developer 1. Debug Overlay: What To Draw", "More specific overlay filters and draw limits." },
        { "PhysicsInteraction", "bDebugDrawHandBoneColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawBodyBoneColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawDynamicHandColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawHandBoneContacts", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxHandBoneBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxBodyBoneBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawWeaponColliders", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugDrawGrabbedWeaponPartCollider", "Developer 1. Debug Overlay: What To Draw", "Draws the exact current weapon-part collider selected by each active part grip." },
        { "PhysicsInteraction", "bDebugDrawNativeScopeActivation", "Developer 1. Debug Overlay: What To Draw", "Native-scope diagnosis: sight bounds, live camera, exact pre-activation target pose/aim/up guides, write readback, parent/local camera, and HMD guides." },
        { "PhysicsInteraction", "bDebugDrawAuthoredGripActivationZones", "Developer 1. Debug Overlay: What To Draw", "Visualizes the topology-specific authored cone/arc, live approach vector, and optional palm/fingertip collision witnesses. Witnesses are diagnostic only. Also draws the firing-grip reattach cylinders and live palm vectors during part carry." },
        { "PhysicsInteraction", "bDebugDrawWeaponAuthority", "Developer 1. Debug Overlay: What To Draw", "Draws two-handed weapon/hand/FRIK authority frames and mismatch evidence." },
        { "PhysicsInteraction", "bDebugGripFailureTelemetry", "Developer 1. Debug Overlay: What To Draw", "Enables the grip-failure telemetry ring (per-frame snapshots during manual ownership) and full incident dumps. Off: an incident logs one summary line." },
        { "PhysicsInteraction", "bDebugDrawLooseWeaponGripZones", "Developer 1. Debug Overlay: What To Draw", "Draws the loose-weapon projected grip point, palm relation, and equip radius state." },
        { "PhysicsInteraction", "bDebugDrawDynamicWeaponColliders", "Developer 1. Debug Overlay: What To Draw", "Draws the layer-51 dynamic weapon compound proxy and contact/correction telemetry." },
        { "PhysicsInteraction", "bDebugDumpWeaponAnimNodes", "Developer 1. Debug Overlay: What To Draw", "Logs first-person Weapon/WeaponLeft/AnimObject/Projectile anchors, transforms, child names, and subtree mesh counts. Useful for investigating equipped weapon mod swaps that expose geometry outside ROCK's current collision roots." },
        { "PhysicsInteraction", "iDebugMaxWeaponBodiesDrawn", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugWeaponAnimNodeDumpIntervalFrames", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCapturesPerFrame", "Developer 1. Debug Overlay: What To Draw", "Bounded overlay work and memory budgets. Zero disables the corresponding capture/upload/draw stream where noted. Ranges: captures 0..32, compound slots 1..1024, depth 1..8, queued/completed 0..256, uploads 0..16, cache entries 16..4096, cache bytes 1048576..536870912, body instances 0..171, line vertices 0..65536, text vertices 0..131072." },
        { "PhysicsInteraction", "iDebugMaxConvexSupportVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxCompoundChildren", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxCompoundDepth", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeQueuedJobs", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCompletedJobs", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeUploadsPerFrame", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCacheEntries", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxShapeCacheBytes", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxBodyInstances", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxLineVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "iDebugMaxTextVertices", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugUseBoundsForHeavyConvex", "Developer 1. Debug Overlay: What To Draw", "" },
        { "PhysicsInteraction", "bDebugVerboseLogging", "Developer 2. Debug Logs, Telemetry, And Notifications", "Very noisy per-frame diagnostic logging. Use only while investigating a specific issue." },
        { "PhysicsInteraction", "bDebugGrabFrameLogging", "Developer 2. Debug Logs, Telemetry, And Notifications", "Focused logs for grab frame capture and held-object transform comparisons." },
        { "PhysicsInteraction", "bDebugVideoSyncMarker", "Developer 2. Debug Logs, Telemetry, And Notifications", "Optional video synchronization marker used only during diagnostics." },
        { "PhysicsInteraction", "fDebugVideoSyncMarkerSize", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabTimelineTrace", "Developer 2. Debug Logs, Telemetry, And Notifications", "Structured per-grab timeline rows for capture, constraint writes, solver response, and release. Use this when building graphs from ROCK.log. Very noisy when enabled." },
        { "PhysicsInteraction", "iDebugGrabTimelineTraceIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabAfterSolveAnomalySampling", "Developer 2. Debug Logs, Telemetry, And Notifications", "Sample after-solve proxy/body mismatch diagnostics without enabling full grab-frame logging. This reads live body and constraint atom state; keep disabled during normal gameplay." },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetry", "Developer 2. Debug Logs, Telemetry, And Notifications", "Timestamp-matched grab telemetry for comparing video, overlay text, and ROCK.log rows." },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryText", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryAxes", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryLogIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryTextMode", "Developer 2. Debug Logs, Telemetry, And Notifications", "0 = duplicate telemetry text into both VR eye halves. 1 = draw one text panel across the submitted texture." },
        { "PhysicsInteraction", "bDebugShowGrabNotifications", "Developer 2. Debug Logs, Telemetry, And Notifications", "In-game popup diagnostics for grab decisions." },
        { "PhysicsInteraction", "bDebugShowWeaponNotifications", "Developer 2. Debug Logs, Telemetry, And Notifications", "In-game popup diagnostics for weapon contact and support grip decisions." },
        { "PhysicsInteraction", "bDebugWeaponOmodDump", "Developer 2. Debug Logs, Telemetry, And Notifications", "One-shot research dump per equipped weapon build: installed OMOD records (attach point, model path), generated evidence bindings, and the assembled weapon node tree. Verbose; enable only when collecting part-identity data." },
        { "PhysicsInteraction", "bDebugHandTransformParity", "Developer 2. Debug Logs, Telemetry, And Notifications", "Compares ROCK's direct first-person skeleton hand transforms against the FRIK API path. Diagnostic only. It does not choose the active hand frame." },
        { "PhysicsInteraction", "bDebugHandWorldAuthority", "Developer 2. Debug Logs, Telemetry, And Notifications", "Periodic summary of the FRIK API v2 hand world authority: controller-hand reconstruction source counts and error probe, claim rebase publishes, and pre-FRIK scheduler state. Diagnostic only. Fallback and refusal warnings are always logged." },
        { "PhysicsInteraction", "bDebugWorldObjectOriginDiagnostics", "Developer 2. Debug Logs, Telemetry, And Notifications", "Logs and draws alternate world-origin candidates for selected or held objects. Diagnostic only. It does not change object motion." },
        { "PhysicsInteraction", "iDebugWorldObjectOriginLogIntervalFrames", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "fDebugWorldObjectOriginMismatchWarnGameUnits", "Developer 2. Debug Logs, Telemetry, And Notifications", "" },
        { "PhysicsInteraction", "bDebugShowRootFlattenedFingerSkeletonMarkers", "Developer 3. Skeleton Debug", "Draws markers and axes for live first-person skeleton bones." },
        { "PhysicsInteraction", "bDebugShowSkeletonBoneVisualizer", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugSkeletonBoneMode", "Developer 3. Skeleton Debug", "0 = minimal/core bones, 1 = core body and fingers, higher modes may draw more if supported." },
        { "PhysicsInteraction", "iDebugSkeletonBoneSource", "Developer 3. Skeleton Debug", "Selects the skeleton source used by the debug visualizer." },
        { "PhysicsInteraction", "iDebugMaxSkeletonBonesDrawn", "Developer 3. Skeleton Debug", "Draw limits and filters for skeleton debug drawing." },
        { "PhysicsInteraction", "bDebugDrawSkeletonBoneAxes", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugMaxSkeletonBoneAxesDrawn", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "sDebugSkeletonAxisBoneFilter", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "bDebugLogSkeletonBones", "Developer 3. Skeleton Debug", "Logs bone names and truncation information to ROCK.log." },
        { "PhysicsInteraction", "bDebugLogSkeletonBoneTruncation", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "iDebugSkeletonBoneLogIntervalFrames", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "sDebugSkeletonBoneLogFilter", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "fDebugRootFlattenedFingerSkeletonMarkerSize", "Developer 3. Skeleton Debug", "Marker and axis sizes for skeleton debug visuals." },
        { "PhysicsInteraction", "fDebugSkeletonBonePointSize", "Developer 3. Skeleton Debug", "" },
        { "PhysicsInteraction", "fDebugSkeletonBoneAxisLength", "Developer 3. Skeleton Debug", "" },
        { "Debug", "bDeveloperModeEnabled", "Debug", "Gates advanced/tuning-only features not meant for normal play. Currently: pressing A while holding an object records/overwrites a saved grab offset for that object+hand. Saved offsets keep applying on future grabs regardless of this setting - it only gates recording new ones." },
        { "Debug", "sLogPattern", "Debug", "Text format for each ROCK.log line." },
        { "Debug", "iLogSampleMilliseconds", "Debug", "Minimum time between repeated sampled diagnostic messages." },
        { "Debug", "bPerformanceProfilerEnabled", "Debug", "Async Performance Profiler Independent from iLogLevel. When enabled, timing scopes stay on the frame path, but completed profiler windows are queued to a bounded background writer. Output goes to ROCK_Profiler.log, not ROCK.log. File formatting/writes are not done by grab, reload, physics, or frame update code. If the writer falls behind, profiler windows are dropped instead of stalling gameplay." },
        { "Debug", "iPerformanceProfilerLogIntervalFrames", "Debug", "Number of frames per queued profiler window after warmup. Larger values reduce file traffic." },
        { "Debug", "iPerformanceProfilerWarmupFrames", "Debug", "Startup/reload frames ignored before profiler windows are emitted." },
        { "Debug", "bPerformanceProfilerOverlayText", "Debug", "Draws latest profiler window as in-game overlay text. Leave false for clean file-only profiling." },
    };
}
