#pragma once

#include "api/ROCKConfigurationApi.h"
#include <string_view>

namespace rock::config
{
    struct SettingMetadata
    {
        std::string_view section, key, category, description;
        configuration_api::Group group;
    };

    // Presentation order, grouping, and help for INI creation and the wheel menu.
    // Setting types and defaults remain owned by the compiled loader.
    inline constexpr SettingMetadata kSettingMetadata[] = {
        { "Logging", "iLogLevel", "01. Logging", "ROCK.log detail level for normal plugin messages.\nModes: 0=trace, 1=debug, 2=info, 3=warn, 4=error, 5=critical, 6=off.\nTrace/debug/info can be expensive if hot-path diagnostics are enabled.\nSet 6 to keep the main ROCK.log silent during performance testing.", configuration_api::Group::Consumer },
        { "RealisticWeapons", "bImmersiveGrenades", "02. Grenades", "Hold B draws an immersive grenade.\nFalse uses vanilla hold/release throwing instead. PALM uses right trigger + grab.\nRelease B before changing modes. Grenades already drawn or armed keep their existing behavior.", configuration_api::Group::Consumer },
        { "RealisticWeapons", "fRealisticGrenadeFuseSeconds", "02. Grenades", "Seconds from pin pull to ROCK detonation. Set 0 to use the grenade projectile's native fuse timer.", configuration_api::Group::Consumer },
        { "ImmersiveAid", "bEnabled", "03. Immersive Aid", "Fixed Stimpak/Med-X grips and automatic injection after 0.5 seconds of body contact.\nFalse restores ordinary grabs and mouth consumption for these aid items.\nRelease and grab again after changing this mode to change an existing grip pose.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bBipodMode", "04. Weapon Handling", "Bipod Mode: right-stick click latches any equipped weapon part to a surface.\nFalse releases the latch and leaves the click available to other input handlers.\nWhile latched, ROCK recoil uses a fixed 10% profile, regardless of hand count or armor.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bDetachEitherHand", "04. Weapon Handling", "Detach Either Hand\nAllows either hand to detach from the weapon, including the hand on the firing grip.\nFiring and support grips follow Weapon Grab Mode, on either hand.\nAttach-only parts always release with the button.\nThe other hand keeps holding the weapon until its grip is released.\nAuto Drop below controls whether the last grip transfers the weapon into a held loose object.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bFiringGripDetachPosePreservationEnabled", "04. Weapon Handling", "Keeps the weapon's position and rotation at the final two-hand pose when the\nfiring grip detaches into support-hand part carry. Subsequent support-hand\nmotion moves the weapon from that pose without an initial correction.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bAutoDrop", "04. Weapon Handling", "Auto Drop: equipped weapon to held loose weapon\nReleasing the last carrying grip unequips the weapon into that hand.\nToggle grips: press again to transfer. Hold grips: release the held grab button.\nThe loose weapon stays held after the initiating button release.\nPress grab again, then release to drop or stash it; trigger equips it again.\nWhen false, the last carrying grip stays attached; hand transfers remain available.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "iWeaponGrabMode", "04. Weapon Handling", "Weapon Grab Mode\n1 = Toggle both grips. 2 = Toggle firing grip only. 3 = Hold both grips.\nMode 2 follows the firing role on either hand; support grips must stay held.\nToggle grips release on the next press; hold grips release with the button.\nAttach-only weapon parts always require holding grab.\nAuto Drop transfers the last released grip into a retained loose grab.\nOrdinary loose objects and surfaces use hold-to-grab. Auto Drop weapons remain held until a later grab press and release.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bGrabAnywhereOnWeapon", "04. Weapon Handling", "Grab Anywhere on Weapon\nTrue: allow dynamic support grabs anywhere on the weapon.\nFalse: use authored support grips where available (default).\nWeapons without an authored support pose keep their dynamic-grab fallback.\nApplies to either support hand and is independent of Ambidextrous Firing.\nAuthored grips and ROCK API weapon-part targets keep their existing priority.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fFiringGripReattachRadiusGameUnits", "04. Weapon Handling", "Shared reach of the firing-grip handoff and reattach cylinders in game units.\nEach cylinder starts at the firing grip and extends along one lateral side.\nPress grab inside to attach the receiving hand; tap the current firing hand's\ngrab button to transfer. Detached firing-grip reattachment uses the same zone.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fFiringGripReattachCylinderRadiusGameUnits", "04. Weapon Handling", "Radius in game units of each firing-grip reattach cylinder: how far the palm may\nsit off the lateral axis anywhere along the reach.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fGripZoneIndicatorDiameterGameUnits", "04. Weapon Handling", "Diameter of the permanent grip-zone sphere in game units. Valid range: 0.10..5.00.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fFiringGripHapticDurationSeconds", "04. Weapon Handling", "Successful firing-grip attach and detach transition pulses on the acting hand.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fFiringGripAttachHapticIntensity", "04. Weapon Handling", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fFiringGripDetachHapticIntensity", "04. Weapon Handling", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "bImmersiveRecoil", "05. Weapon Recoil", "Enables all ROCK visual recoil profiles for either hand, including power armor.\nFalse leaves recoil to FRIK and clears pending ROCK recoil.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fPistolOneHandRecoilPercent", "05. Weapon Recoil", "Recoil percentages when not surface-latched or in power armor: 0 = none, 100 = unscaled hold profile, 300 = triple.\nOneHand applies without a support grip; TwoHand preserves the full/close support profile.\nBipod support and power armor override both controls. Values are limited to 0..300.", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fPistolTwoHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fRifleOneHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fRifleTwoHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fShotgunOneHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fShotgunTwoHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fHeavyOneHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fHeavyTwoHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fDefaultOneHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "ImmersiveWeapons", "fDefaultTwoHandRecoilPercent", "05. Weapon Recoil", "", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "bAmbidextrousFiringGripEnabled", "06. Handedness", "ROCK's standalone/fallback firing-grip policy. Either hand can inherit the\nfiring grip when the current firing hand opens while the other hand is\nwrapped over it. A loose weapon held in the left hand can also be equipped\ndirectly with that same hand's trigger. The Immersive Weapons firing-grip\ndetach feature is independent and never forces this handoff mode or its\nleft-firing aim tuning. When immersive detach is disabled, firing ownership\nchanges only through the independent handoff, direct trigger-equip,\nexternal/native holster, or weapon-state cleanup paths.", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fFiringGripPromotionRadius", "06. Handedness", "Promotion reach for an ordinary support grip when the firing hand detaches.\nDirect firing-grip handoff detection and transfer instead use the shared\nfFiringGripReattachRadiusGameUnits and fFiringGripReattachCylinderRadiusGameUnits.", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fLeftFiringAimYawDegrees", "06. Handedness", "Optional global correction for ROCK's mirrored left firing hold.", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fLeftFiringAimPitchDegrees", "06. Handedness", "", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fLeftFiringAimOffsetXGameUnits", "06. Handedness", "", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fLeftFiringAimOffsetYGameUnits", "06. Handedness", "", configuration_api::Group::Consumer },
        { "AmbidextrousFiring", "fLeftFiringAimOffsetZGameUnits", "06. Handedness", "", configuration_api::Group::Consumer },
        { "NativeScopes", "bEnableImmersiveScopes", "07. Scopes", "True enables ROCK scope positioning, button-hold activation, and overlay/zoom corrections.\nFalse restores vanilla cone-based activation and native camera, overlay, and zoom behavior.\nRelease A/X before changing modes. Firing-hand reload remains available.", configuration_api::Group::Consumer },
        { "NativeScopes", "fManualScopeHoldSeconds", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "bNativeScopeForceFiringGripFallback", "07. Scopes", "Missing or unusable generated Scope/Sight geometry falls back to the current\nfiring-grip palm seat. Set the force switch only when ROCK accepts a bad\noptic collider and you need to bypass it while tuning. Offsets are game units\nfrom that firing-grip origin in Weapon-local axes: X lateral, +Y muzzle\nforward, and Z vertical. Zeroes place the anchor exactly at the firing grip.\nRotations are additive degrees after native camera calibration: pitch about\nX, yaw about Z, and roll about +Y/the muzzle axis. Position moves activation,\ncamera, and overlay together; rotation corrects the camera and overlay only.", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackOffsetXGameUnits", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackOffsetYGameUnits", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackOffsetZGameUnits", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackPitchDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackYawDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeFiringGripFallbackRollDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayOffsetXGameUnits", "07. Scopes", "Fine-tunes only FO4VR's game-native world_scope.nif overlay. ROCK keeps the\nactivation camera on the resolved generated-sight/firing-grip anchor\nindependently, so these values do not change when the native scope activates.\nZero values keep automatic anchor placement plus Bethesda's native\nmodel orientation/scale. Offsets are game units in the calibrated model-local\nframe. Rotations are degrees: pitch about local X, yaw about local Z, and roll\nabout the optical/depth Y axis. Tune one axis at a time; loose replacement\nNIFs can use a visually reversed sign convention.", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayOffsetYGameUnits", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayOffsetZGameUnits", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayPitchDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayYawDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "NativeScopes", "fNativeScopeOverlayRollDegrees", "07. Scopes", "", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "bSuppressNativeVats", "08. Controller Input", "Blocks only ordinary VATS, which fires when the native VATS button is released.\nThe raw OpenVR button remains readable.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "fPipboyPauseHoldSeconds", "08. Controller Input", "ROCK owns the native Pause button during gameplay. Releasing it before this\nthreshold opens the Pip-Boy; holding through the threshold opens Pause. On\nQuest 2 this is Y in right-handed mode and follows Bethesda's secondary-wand\nmapping in left-handed mode. The old trigger-release Pip-Boy open is disabled.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "bGrabInputIntentStateEnabled", "08. Controller Input", "Keeps a grab press alive briefly while selection, pull catch, or input suppression settles.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "fGrabInputLeewaySeconds", "08. Controller Input", "", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "fGrabInputForceSeconds", "08. Controller Input", "", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "bEnableVanillaMelee", "09. Native Gameplay", "Enables vanilla Fallout VR player melee. True allows every native\nreal-weapon input, swing, hit-frame, impact, damage, and VRInput-setting path.\nFalse suppresses that complete chain. NPC melee always passes through.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "bNativeCharacterControllerObjectContactFilterEnabled", "09. Native Gameplay", "Filters only the native player character-controller bubble contacts.\nKeeps world/support blocker layers, but prevents the vanilla bubble from pushing clutter, guns, actors, ragdolls, and ROCK-generated bodies.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "bHighlightEnabled", "10. Selection Feedback", "Highlights the object ROCK thinks your hand can grab.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "iHighlightIntensityMode", "10. Selection Feedback", "ROCK-owned grab highlight intensity: 1=40%, 2=60%, 3=80%, 4=100%.", configuration_api::Group::Consumer },
        { "PhysicsInteraction", "sHighlightColor", "10. Selection Feedback", "ROCK-owned grab highlight color: red, blue, orange, or white.", configuration_api::Group::Consumer },
        { "Debug", "bDeveloperModeEnabled", "01. Developer Controls", "Gates advanced/tuning-only features not meant for normal play. Currently:\npressing A while holding an object records/overwrites a saved grab offset\nfor that object+hand. Saved offsets keep applying on future grabs\nregardless of this setting - it only gates recording new ones.", configuration_api::Group::Developer },
        { "Debug", "sLogPattern", "02. Logging and Profiling", "Text format for each ROCK.log line.", configuration_api::Group::Developer },
        { "Debug", "iLogSampleMilliseconds", "02. Logging and Profiling", "Minimum time between repeated sampled diagnostic messages.", configuration_api::Group::Developer },
        { "Debug", "bPerformanceProfilerEnabled", "02. Logging and Profiling", "Asynchronous performance profiler.\nIndependent from iLogLevel. When enabled, timing scopes stay on the frame path,\nbut completed profiler windows are queued to a bounded background writer.\nOutput goes to ROCK_Profiler.log, not ROCK.log. File formatting/writes are not done\nby grab, reload, physics, or frame update code. If the writer falls behind, profiler\nwindows are dropped instead of stalling gameplay.", configuration_api::Group::Developer },
        { "Debug", "iPerformanceProfilerLogIntervalFrames", "02. Logging and Profiling", "Number of frames per queued profiler window after warmup. Larger values reduce file traffic.", configuration_api::Group::Developer },
        { "Debug", "iPerformanceProfilerWarmupFrames", "02. Logging and Profiling", "Startup/reload frames ignored before profiler windows are emitted.", configuration_api::Group::Developer },
        { "Debug", "bPerformanceProfilerOverlayText", "02. Logging and Profiling", "Draws latest profiler window as in-game overlay text. Leave false for clean file-only profiling.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceX", "03. Palm and Grab Offsets", "Legacy authored palm pivot used by API palm position, telemetry, debug tuning,\ntwo-handed grip, and non-dynamic helpers.\nDynamic object grabs use the generated hidden proxy authority pivot below.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceY", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabLegacyPalmPivotAHandspaceZ", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceX", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceY", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabLegacyPalmPivotAHandspaceZ", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetXGameUnits", "03. Palm and Grab Offsets", "Local offset for the hidden grab authority proxy/seat point, in corrected palm proxy space.\nX follows the fingers, -Y moves into the palm face/skin, +Y moves to the back of the hand,\nand Z moves across the palm. This does not move the real palm/finger physics colliders.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetYGameUnits", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fRightGrabAuthorityProxyOffsetZGameUnits", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetXGameUnits", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetYGameUnits", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fLeftGrabAuthorityProxyOffsetZGameUnits", "03. Palm and Grab Offsets", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bWeaponCollisionBlocksProjectiles", "04. Weapon Collision and Support", "Controls whether ROCK weapon hulls collide with projectile/spell layers.\nFalse avoids self-collisions with modded projectile systems while aiming.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bWeaponCollisionBlocksSpells", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bWeaponCollisionPreserveGaps", "04. Weapon Collision and Support", "False: original convex fitting. True: bounded gap-preserving compounds.\nChanging this key rebuilds weapon colliders after live INI reload.\nCompare with bPerformanceProfilerEnabled: weaponColliderBuild/Create vs weaponGapColliderBuild/Create.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponCollisionVisualStabilizationSeconds", "04. Weapon Collision and Support", "Seconds ROCK waits for the visual weapon tree to stay visible/stable before replacing generated hulls after weapon/mod swaps.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponCollisionMaxLinearVelocity", "04. Weapon Collision and Support", "Maximum speed allowed when ROCK keyframes generated weapon hulls.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponCollisionMaxAngularVelocity", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponCollisionGripRecoveryDistanceGameUnits", "04. Weapon Collision and Support", "Immediately resets a failed dynamic weapon collider onto the firing hand if\nits live firing-grip authority point is farther away than this distance.\nThis catastrophic-failure limit is separate from normal wall-contact\nconvergence. 210 game units is about 3 metres. Game units (~1.4cm each).", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponInteractionTouchRadius", "04. Weapon Collision and Support", "Small sphere around each configured legacy palm pivot. If it overlaps a\ngenerated weapon collider, the grab uses ROCK's unrestricted dynamic seat.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponInteractionProbeRadius", "04. Weapon Collision and Support", "Broader per-hand search used when the palm is not touching the weapon.\nWith authored weapon grips enabled, a grab acquired only by this probe uses\nthe modeler's authored firing/support seat instead of the dynamic mesh seat.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fFiringGripProximitySupportRadius", "04. Weapon Collision and Support", "Every support grab inside this distance from the firing grip stays visual-only\nso pistols retain a stable support pose without competing weapon authority.\nROCK always owns this behavior. An active equipped-weapon addon may override\nonly the radius through the ROCK V1 API. Game units (~1.4cm each).", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bWeaponSupportGripHandLerpEnabled", "04. Weapon Collision and Support", "Eases ROCK's external FRIK hand target into an equipped weapon support grip.\nThis is visual-only: weapon aim authority remains immediate.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpTimeMin", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpTimeMax", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpMinDistance", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponSupportGripHandLerpMaxDistance", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bWeaponSupportSurfaceSeatEnabled", "04. Weapon Collision and Support", "Seats the visual support palm toward the contacted surface without rotating the weapon.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fWeaponSupportSurfaceSeatMaxDegrees", "04. Weapon Collision and Support", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bBodyBoneCollidersEnabled", "05. Hand and Body Collision", "Creates generated keyframed colliders for the torso, arms, legs, and feet.\nFalse disables the entire body set while leaving hand and finger colliders alive.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bBodyBoneLegAndFootCollidersEnabled", "05. Hand and Body Collision", "Adds leg and foot colliders to the generated body set.\nFalse keeps torso and arm colliders while omitting every leg and foot body.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderStandardRadiusScale", "05. Hand and Body Collision", "Global generated body collider size scales. Power armor starts from a separate larger descriptor set, then applies these scales.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderStandardLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderStandardConvexRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderPowerArmorConvexRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderTorsoRadiusScale", "05. Hand and Body Collision", "Role-specific scales applied after the standard/power-armor profile scale.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderArmRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderLegRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderFootRadiusScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderTorsoLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderArmLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderLegLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fBodyBoneColliderFootLengthScale", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sBodyBoneColliderZoneScaleOverrides", "05. Hand and Body Collision", "Optional descriptor-specific size overrides for tuning stash/holster/backpack zones.\nFormat: Zone=radius,length,convex;PowerArmor.Zone=radius,length,convex\nZone names: Pelvis, SpineLower, SpineUpper, Chest, NeckHead, LeftShoulder, LeftUpperArm, LeftForearmUpper,\nLeftForearmLower, LeftHand, RightShoulder, RightUpperArm, RightForearmUpper, RightForearmLower, RightHand,\nLeftHip, LeftThigh, LeftCalf, LeftFoot, RightHip, RightThigh, RightCalf, RightFoot.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sBodyBoneColliderRadiusScaleOverrides", "05. Hand and Body Collision", "Optional individual generated body collider radius scale overrides.\nFormat: Zone=radiusScale;StartBone>EndBone=radiusScale;PowerArmor.Zone=radiusScale;PowerArmor.StartBone>EndBone=radiusScale\nExamples: LeftForearmLower=0.85;RArm_ForeArm2>RArm_ForeArm3=0.90;PowerArmor.Chest=1.10", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bHandCollisionStaticWorldEnabled", "05. Hand and Body Collision", "Allows generated hand colliders to collide with static/animstatic world geometry for native contact evidence.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGlobalSurfaceGrabEnabled", "05. Hand and Body Collision", "Makes dynamic-hand world-surface contacts eligible for fixed-anchor grab fallback.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bSurfaceMeshGrabEnabled", "05. Hand and Body Collision", "Uses the contacted render mesh as the spatial authority for fixed-surface grabs.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSurfaceMeshGrabMaxProjectionDistanceGameUnits", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iSurfaceMeshGrabMaxTriangles", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sHandBoneColliderRadiusScaleOverrides", "05. Hand and Body Collision", "Optional generated hand capsule-like collider radius scale overrides. Palm-box roles are controlled by X/Y/Z below.\nRole names: ThumbBase, ThumbMiddle, ThumbTip, IndexBase, IndexMiddle, IndexTip, MiddleBase, MiddleMiddle,\nMiddleTip, RingBase, RingMiddle, RingTip, PinkyBase, PinkyMiddle, PinkyTip.\nFormat: Role=radiusScale;PowerArmor.Role=radiusScale", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sHandPalmColliderDimensionScaleOverrides", "05. Hand and Body Collision", "Optional generated palm-box collider local dimension scale overrides.\nLocal X=fingers/segment length, local Y=palm depth, local Z=cross-palm width.\nRole names: PalmAnchor, PalmFace, PalmBack, PalmHeel, ThumbPad.\nFormat: Role=xScale,yScale,zScale;PowerArmor.Role=xScale,yScale,zScale", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bHandBoneCollidersRequirePalmAnchor", "05. Hand and Body Collision", "Requires the palm anchor before creating hand bone colliders.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHandBoneColliderMaxLinearVelocity", "05. Hand and Body Collision", "Speed clamps for bone-driven hand colliders.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHandBoneColliderMaxAngularVelocity", "05. Hand and Body Collision", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bPullToObjectCenterEnabled", "06. Selection and Pulling", "Far grabs pull the object's CENTER to the hand instead of the ray-hit point\n(a hit at selection range is aim noise, not grip intent). The arrival seat\nthen settles the surface onto the palm via the seat machinery.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bPullLongAxisPresentationEnabled", "06. Selection and Pulling", "Long-object presentation during pull flight: rotates elongated props (brooms,\nbottles) so their mesh long axis lines up with the hand's thumb->pinky line\nbefore arrival. Flight-only; held objects are never rotated. Elongation is the\nRMS extent ratio between the mesh's dominant and second axis (compact objects\n~1 skip presentation). Gain is proportional rad/s per rad of error.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullPresentationMinElongationRatio", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullPresentationAngularGainPerSecond", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullPresentationMaxAngularSpeedRadiansPerSecond", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullPresentationGripAxisTiltDegrees", "06. Selection and Pulling", "Tilts the presentation target off pure cross-palm Z toward fingers-forward\n+X, in degrees (0..45): the thumb occupies the pure-Z line, so the natural\nlong-object hold sits a few degrees toward the fingertips. Applies to both\nthe pull-flight servo and the force-grab seat alignment.\nThis is an anatomical magnitude, not a signed rotation. Authored Z reverses\nits cross-palm direction between hands, but +X points toward the fingertips\non both. ROCK resolves the live axes first, then tilts each signed Z axis\ntoward its own +X, so one value has the same meaning for both hands.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bForceGrabSeatAlignmentEnabled", "06. Selection and Pulling", "Applies long-axis presentation alignment to force-grab arrival seats.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabSeatRollAlignmentEnabled", "06. Selection and Pulling", "Applies face-to-palm roll alignment to programmatic arrival seats.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSeatRollMinSecondElongationRatio", "06. Selection and Pulling", "Shape-classification gate shared by the flight presentation servo and the\ngrab pose solver: sqrt(lambda2/lambda3) of the mesh PCA at or above this\nratio marks a distinct flat face (plate class). The solver uses the class\nfor its rod-only terms; plates keep their edge/corner holds (31 verified\nplate holds put the face normal 63 deg off the palm normal - edge holds are\nthe intended grip, not an artifact).", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iObjectPhysicsTreeMaxDepth", "06. Selection and Pulling", "Maximum scene-node depth used when scanning an object for physics bodies.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDynamicPushAssistEnabled", "06. Selection and Pulling", "Lets moving hands or weapon hulls nudge already-dynamic props.\nIt never converts static or keyframed objects into dynamic objects.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDynamicPushMinSpeed", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDynamicPushMaxImpulse", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDynamicPushCooldownSeconds", "06. Selection and Pulling", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLinearTau", "07. Grab Drive", "Custom dynamic-grab drive used by all loose object holds.\nThe held object uses finite linear/angular motors against a hidden no-contact\nproxy. Translation comes from the live palm/proxy anchor, while rotation comes\nfrom the root-flattened raw hand/controller frame.\nLinear shared-constraint motor response. Lower tau is stiffer and faster. Higher damping calms oscillation.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLinearDamping", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLinearProportionalRecovery", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLinearConstantRecovery", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAngularTau", "07. Grab Drive", "Angular shared-constraint motor response. Same idea as linear motor, but for rotation.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAngularDamping", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAngularProportionalRecovery", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAngularConstantRecovery", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabConstraintMaxForce", "07. Grab Drive", "Maximum force the grab constraint can apply.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabEffectiveMotorMassFloorEnabled", "07. Grab Drive", "Keeps the motor's effective mass finite for very light or unstable bodies.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabEffectiveMotorMassFloor", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabPhysicsRateForceScalingEnabled", "07. Grab Drive", "Controlled locomotion-stutter A/B (2026-08-22): keep the ordinary-object\nmotor at the configured 2000 force on every Havok substep. The prior default\nmultiplied force by sqrt(90 / physicsHz), producing about 1643-2245 force as\nFO4VR alternated between 7.5 ms and 14 ms substeps. Remove this test override\nafter the constant-force result is decided.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPhysicsRateReferenceHz", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPhysicsRateForceScaleExponent", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPhysicsRateMinForceScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPhysicsRateMaxForceScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMaxForceToMassRatio", "07. Grab Drive", "Caps force by object mass so light objects do not explode out of the hand.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fForceGrabAttachSettleSeconds", "07. Grab Drive", "Waits for a stable live hand transform before a force grab freezes its relation.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabForceFadeInTime", "07. Grab Drive", "Time for grab force to ramp in after pickup.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearTauMultiplier", "07. Grab Drive", "Multipliers for non-equipped weapon refs grabbed as loose dynamic objects.\nLoose weapons keep the same mass cap as generic objects, but get the\na higher base force before that cap is applied. Angular force is\nseparate so long multipart weapons can rotate without increasing linear pull.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularTauMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintCollisionTauMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearDampingMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularDampingMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintMaxForceMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularForceMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintLinearRecoveryMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLooseWeaponSharedConstraintAngularRecoveryMultiplier", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabTauMin", "07. Grab Drive", "Contact-softened tau. Normal held linear/angular tau stay fixed at their base values.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabTauLerpSpeed", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabLongObjectAngularScalingEnabled", "07. Grab Drive", "Reduces held angular speed for long objects by grip-to-extents lever length.\nThis keeps long guns/objects from sweeping as if their far end had no leverage.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLongObjectReferenceLeverGameUnits", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLongObjectMinAngularScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabPivotQualityAngularScalingEnabled", "07. Grab Drive", "Limits release angular velocity when the grab pivot has weak normal/contact support.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPositionOnlyAngularScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSmallObjectReferenceLeverGameUnits", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSmallObjectAngularScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLowContactSupportAngularScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMinAngularAuthorityScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabWeakPivotTwistScale", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMaxInertiaRatio", "07. Grab Drive", "Clamps extreme inertia tensors on grabbed rigid bodies to keep the solver stable.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMinInertia", "07. Grab Drive", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMaxDeviation", "08. Grab Safety and Release", "Force-releases if the held object stays too far from the palm for too long.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMaxDeviationTime", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fThrowVelocityMultiplier", "08. Grab Safety and Release", "Multiplies held-object velocity when you release to throw.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabControllerDerivedThrowVelocityEnabled", "08. Grab Safety and Release", "Uses tracked hand velocity, COM-relative angular swing, and a small object-velocity blend for throws.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThrowObjectVelocityBlend", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThrowTangentialVelocityScale", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThrowMaxVelocityHavok", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThrowAngularVelocityScale", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThrowMaxAngularVelocityRadiansPerSecond", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabReleaseHandCollisionDelaySeconds", "08. Grab Safety and Release", "Keeps hand collision suppressed briefly after release so the object is not launched instantly.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bShoulderStashEnabled", "08. Grab Safety and Release", "Shoulder stash transfers a held loose item to inventory when grip is released inside the HMD-relative back volume.\nGenerated FRIK body-zone colliders are backup evidence for tracking loss and remain the preferred path for holsters.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bEquippedWeaponShoulderStashEnabled", "08. Grab Safety and Release", "Equipped weapons use the same HMD-relative back volumes and remain equipped.\nToggle-grab: press inside to sheath or retrieve; release only rearms.\nHold-to-grab: hold inside and release to sheath; press inside to retrieve,\nthen pull forward or release while the weapon remains drawn.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bShoulderStashUseBodyZoneColliders", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bShoulderStashUseHmdBackVolume", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashEnterPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashExitPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashMinDwellSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashMaxSpeedGameUnitsPerSecond", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashRecentContactSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashSustainedContactMissSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetXGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetYGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackRightOffsetZGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetXGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetYGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackLeftOffsetZGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackRadiusGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackEnterPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackExitPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashHmdBackMinBehindGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bShoulderStashShowCollectedNotifications", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bMouthConsumeEnabled", "08. Grab Safety and Release", "Mouth consume uses a tight HMD-relative sphere near the mouth.\nOnly loose ALCH ingestibles can become mouth candidates; other objects use backpack stash/drop paths.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bMouthConsumeAllowPoison", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetXGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetYGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeHmdOffsetZGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeRadiusGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeEnterPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeExitPaddingGameUnits", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeMinDwellSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeMaxSpeedGameUnitsPerSecond", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabNearbyDampingEnabled", "08. Grab Safety and Release", "Removes leftover object velocity while held. 0=no damping, 1=stop instantly.\nPreserves player locomotion separately from held-object residual velocity.\nStick-locomotion held-object stutter fix (stage 2): de-aliases the grab proxy target with the\naligned ApplyMovementDelta room delta. DISABLED: the aligned signal is the commanded player\nmovement, not the room-node motion the held object follows, so it saturated and did nothing.\nTemporarily calms nearby dynamic clutter when a grab starts.\nUses verified FO4VR hknp motion-property damping leases with safe restore.\nDamping values are hknp per-second coefficients, not normalized percentages.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabNearbyDampingRadius", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabNearbyDampingSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabNearbyLinearDamping", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabNearbyAngularDamping", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabHeldMassMovementSlowdownEnabled", "08. Grab Safety and Release", "Reduces player movement speed while carrying held mass.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHeldMassMovementMassProportion", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHeldMassMovementMassExponent", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHeldMassMovementMaxReduction", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHeldMassMovementFadeOutSeconds", "08. Grab Safety and Release", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabTouchAcquireDistanceGameUnits", "09. Grab Acquisition", "Distance from the hand pocket where an object is considered already touching.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabNearConvergeDistanceGameUnits", "09. Grab Acquisition", "Distance where the object should converge into the palm pocket instead of finalizing immediately.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPocketDepthGameUnits", "09. Grab Acquisition", "Hand-pocket offset and radius, in game units, from the root-flattened palm frame.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPocketRadiusGameUnits", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSeatDepthMaxGameUnits", "09. Grab Acquisition", "Legacy seat-depth stop and penetration backstop dimensions, in game units.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSeatDepthFootprintRadiusGameUnits", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSeatPenetrationBackstopFootprintRadiusGameUnits", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSeatDepthSkinGameUnits", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabGripInsetGameUnits", "09. Grab Acquisition", "Moves the captured grip point slightly inside the object from the raw hit/mesh seed.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabConvergeMaxTimeSeconds", "09. Grab Acquisition", "Optional near-converge diagnostic timeout. A value of 0 disables timeout promotion.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabConvergeStableSeconds", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabConvergeMaxSeparatingSpeedGameUnitsPerSecond", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAcquisitionVisualStartDistanceGameUnits", "09. Grab Acquisition", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabMultiFingerContactValidationEnabled", "10. Grab Contact Evidence", "Requires grouped finger contact evidence before trusting a mesh grab.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iGrabContactQualityMode", "10. Grab Contact Evidence", "0 = permissive, 1 = hybrid patch and finger evidence, 2 = strict grouped-finger debug.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iGrabMinFingerContactGroups", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMinFingerContactSpreadGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerContactMeshSnapMaxDistanceGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabSurfaceBehindPalmToleranceGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabOppositionContactMaxAgeSeconds", "10. Grab Contact Evidence", "Maximum age in seconds for semantic contacts used as touch evidence.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabPinchPocketEnabled", "10. Grab Contact Evidence", "Small-object pinch pocket. Chosen only at close-grab commit, then frozen for the hold.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabPinchCloseSelectionEnabled", "10. Grab Contact Evidence", "Allows a fallback close-selection cast along the pinch direction when the palm close cast misses.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchCompactMaxExtentGameUnits", "10. Grab Contact Evidence", "Compact classification also requires the object's THINNEST extent to fit the\nThinRodMaxCrossSection value below - mugs/cans are compact by size but too\nthick to pinch, so they fall through to the palm grab machinery.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchThinRodMaxLengthGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchThinRodMaxCrossSectionGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchMaxPocketDistanceGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchMinFingerGapGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchMaxFingerGapGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchThumbIndexMaxOpenValue", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchOtherFingerCurlValue", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchSurfaceInsetGameUnits", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceX", "10. Grab Contact Evidence", "Pinch detection direction is authored in ROCK hand space: X=fingers, Y=palm depth, Z=signed cross-palm.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceY", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchDetectionDirectionHandspaceZ", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabPinchDetectionAxisBlend", "10. Grab Contact Evidence", "Blends the live thumb-index axis with the authored pinch direction for mesh surface search.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabHandLerpEnabled", "10. Grab Contact Evidence", "Moves the rendered hand toward the mesh-matched held pose during grab startup.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandLerpTimeMin", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandLerpTimeMax", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandLerpMinDistance", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandLerpMaxDistance", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabHandReturnEnabled", "10. Grab Contact Evidence", "Smooths the rendered hand back to live tracking after releasing a grabbed object.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnTimeMin", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnTimeMax", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnMinDistance", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnMaxDistance", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnMinAngleDegrees", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHandReturnMaxAngleDegrees", "10. Grab Contact Evidence", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabMeshFingerPoseEnabled", "11. Finger Poses", "Computes custom finger curl from the held object's visible mesh.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabMeshJointPoseEnabled", "11. Finger Poses", "Sends per-joint finger values to FRIK when available instead of one curl per finger.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerMinValue", "11. Finger Poses", "Lowest allowed finger value. 0=fully closed, 1=fully straight.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerPoseSmoothingSpeed", "11. Finger Poses", "Maximum per-second finger pose movement.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabMeshLocalTransformPoseEnabled", "11. Finger Poses", "Uses FRIK's authored finger joint transforms plus bounded mesh-contact aim correction.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerLocalTransformSmoothingSpeed", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerLocalTransformMaxCorrectionDegrees", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerSurfaceAimStrength", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabFingerRejectBacksideHits", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerSurfacePlaneToleranceGameUnits", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerSweepContactRadiusGameUnits", "11. Finger Poses", "Swept-arc finger solver: finger-pad contact sphere radius. Bigger = fingers\nstop earlier (hover), smaller = deeper wrap before contact.\nFinger-pad contact radius for the swept-arc solver (0.05-4). The old\nfinger-width air gap was a solver bug (fixed: chord de-rotation), NOT this\nradius - values near 0 now make fingers clip into the mesh.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabFingerSweepMaxOpenValue", "11. Finger Poses", "How far past the authored open pose fingers may hyper-extend when an\nobject is thicker than the open finger span (hFRIK flex units: 1.0 =\nauthored open pose, 2.0 = engine ceiling). The swept-arc close starts\nfrom the most-open allowed row, so a raised cap lets fingers lie flat\non surfaces that interpenetrate the default open hand. Valid range\n1.0-2.0; out-of-range silently falls back (1.4 fingers / 2.0 thumb).", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThumbSweepMaxOpenValue", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThumbOppositionStrength", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThumbAlternateCurveStrength", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabThumbSurfaceSafetyEnabled", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabThumbSurfaceSafetyMarginGameUnits", "11. Finger Poses", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabLateralWeight", "12. Mesh Contact", "Weighting used when choosing the best mesh triangle for grab contact.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabDirectionalWeight", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabMaxTriangleDistance", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabMeshContactOnly", "12. Mesh Contact", "Uses visual mesh as the contact source. Collision still identifies the object body.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabRequireMeshContact", "12. Mesh Contact", "Fails generic close grab when no mesh contact is found. Authored ROCK grab nodes still work.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabContactPatchEnabled", "12. Mesh Contact", "Palm-plane probe patch used to capture the touched object-local point.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iGrabContactPatchProbeCount", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabContactPatchProbeSpacingGameUnits", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabContactPatchProbeRadiusGameUnits", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabContactPatchMeshSnapMaxDistanceGameUnits", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabContactPatchMaxNormalAngleDegrees", "12. Mesh Contact", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabAlignmentMaxSelectionToMeshDistance", "12. Mesh Contact", "Mesh-snap gate used by contact-patch evidence.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bSelectedCloseFingerCurlEnabled", "13. Close-Hand Curl", "Pre-curls the hand when close selection is active.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSelectedCloseFingerAnimMaxHandSpeed", "13. Close-Hand Curl", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSelectedCloseFingerAnimValue", "13. Close-Hand Curl", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bGrabHapticsEnabled", "14. Haptics", "Pulses for grab commit, pull start/catch, and held-object impacts.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHapticBaseIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHapticMaxIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHapticMassScale", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fGrabHapticMassExponent", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullStartHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fPullCatchHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSelectionLockHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSelectionLockReleaseHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSelectionLockReleaseHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bSurfaceGrabHapticsEnabled", "14. Haptics", "Fixed-surface grabs use a longer confirmation pulse.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSurfaceGrabHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fSurfaceGrabHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bHeldImpactHapticsEnabled", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticBaseIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticMaxIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticSpeedScale", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticMassScale", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticMassExponent", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticMinSpeedGameUnits", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticCooldownSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHeldImpactHapticDampedMultiplier", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bShoulderStashHapticsEnabled", "14. Haptics", "Shoulder stash haptics pulse clearly while an item is inside the stash zone, then fire a stronger confirmation on transfer.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticBaseIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCandidateHapticIntervalSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCommitHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fShoulderStashCommitHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bMouthConsumeHapticsEnabled", "14. Haptics", "Mouth consume haptics pulse while a consumable is in the mouth zone, then fire a confirmation on consume.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticBaseIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCandidateHapticIntervalSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCommitHapticDurationSeconds", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fMouthConsumeCommitHapticIntensity", "14. Haptics", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabAuthorityProxy", "14. Haptics", "Draws the hidden no-contact grab authority proxy target/axes used by ROCK dynamic grab.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowColliders", "15. Debug Overlay", "Master switch for all ROCK-owned collider visualizations below.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowTargetColliders", "15. Debug Overlay", "Draws the selected or held target body when the collider master is enabled.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawColliderPhaseDiagnostics", "15. Debug Overlay", "Adds current-target, pre-step, post-solve, predicted-presentation shells,\nand their capture data when the collider master is enabled.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowHandAxes", "15. Debug Overlay", "Draws live transform axes. Red=X, green=Y, blue=Z.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabPivots", "15. Debug Overlay", "Draws grab constraint pivots and the error line between hand-side and object-side pivots.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArc", "15. Debug Overlay", "Swept-arc finger solver visualization.\nThis is independent of bDebugShowGrabFingerProbes (the legacy straight/pad\nprobe overlay). It reads the one-shot swept solve captured at grab time and\nnever re-runs mesh queries. Pinch intentionally remains on its separate path.\nCyan=Tip arc, green=Outer arc, purple=Inner arc, yellow=selected contact\nsphere, white=hit normal/live finger skeleton. Red/magenta/blue/orange mark\nmiss fallback, close-limit hit, out-of-reach, and over-open respectively.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcText", "15. Debug Overlay", "Adds per-finger state/value/probe/lane labels and BVH work totals.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabFingerSweptArcLiveSkeleton", "15. Debug Overlay", "Draws the current rendered finger chains for direct comparison with the arcs.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabFingerProbes", "15. Debug Overlay", "LEGACY ONLY: draws the former straight and pad probes. It is unrelated to the\nswept-arc visualization above.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabPocketNormal", "15. Debug Overlay", "Draws the resolved mesh surface frame after a dynamic grab.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabContactPatch", "15. Debug Overlay", "Draws accepted contact-patch points used to fit the grab surface.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorque", "15. Debug Overlay", "Draws a focused held-grab pivot force/lever view: target pivot, live pivot, correction vector, lever arm, and torque witness.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabForceTorqueText", "15. Debug Overlay", "Adds a compact world label to the focused grab force/lever view.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceCollider", "15. Debug Overlay", "Draws the hknp body/collider that owns the frozen object-side pivot B.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabPivotSourceEvidence", "15. Debug Overlay", "Draws the mesh triangle/contact-patch evidence that produced the frozen pivot.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabSupportFrame", "15. Debug Overlay", "Draws the frozen grab support face frame at pivot B: normal, support axis, and binormal.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabPockets", "15. Debug Overlay", "Draws the live palm pocket and thumb/index pinch pocket for each hand.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowPalmVectors", "15. Debug Overlay", "Draws palm center plus close/far selection aim rays.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawHandColliders", "15. Debug Overlay", "More specific overlay filters and draw limits.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawHandBoneColliders", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawBodyBoneColliders", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawDynamicHandColliders", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawHandBoneContacts", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxHandBoneBodiesDrawn", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxBodyBoneBodiesDrawn", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawWeaponColliders", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawGrabbedWeaponPartCollider", "15. Debug Overlay", "Draws the exact current weapon-part collider selected by each active part grip.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawNativeScopeActivation", "15. Debug Overlay", "Native-scope diagnosis: sight bounds, live camera, exact pre-activation target pose/aim/up guides, write readback, parent/local camera, and HMD guides.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugNativeScopeShotAlignment", "15. Debug Overlay", "Stereo 3D shot panel, visible inside and outside native scopes.\nShows horizontal/vertical ray separation at a shared plane 1500 game units from the sight, including different ray origins.\nPre-fire, at-fire and next-view comparisons stay distinct; next view includes recoil and movement.\nGreen scope, cyan muzzle, yellow native aim and magenta shot. Samples stay for 8 seconds.\nContact comes from physics independently of collider-debug toggles.\nWrites ROCK_ScopeShots.log at most four samples/second. Straight aim guides do not predict impact. No aiming or projectile writes.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawAuthoredGripActivationZones", "15. Debug Overlay", "Visualizes the topology-specific authored cone/arc, live approach vector, and\noptional palm/fingertip collision witnesses. Witnesses are diagnostic only.\nAlso draws the firing-grip reattach cylinders and live palm vectors during part carry.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawWeaponAuthority", "15. Debug Overlay", "Draws two-handed weapon/hand/FRIK authority frames and mismatch evidence.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGripFailureTelemetry", "15. Debug Overlay", "Enables the grip-failure telemetry ring (per-frame snapshots during manual\nownership) and full incident dumps. Off: an incident logs one summary line.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawLooseWeaponGripZones", "15. Debug Overlay", "Draws the loose-weapon projected grip point, palm relation, and equip radius state.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawDynamicWeaponColliders", "15. Debug Overlay", "Draws the layer-51 dynamic weapon compound proxy and contact/correction telemetry.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDumpWeaponAnimNodes", "15. Debug Overlay", "Logs first-person Weapon/WeaponLeft/AnimObject/Projectile anchors, transforms, child names, and subtree mesh counts.\nUseful for investigating equipped weapon mod swaps that expose geometry outside ROCK's current collision roots.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxWeaponBodiesDrawn", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugWeaponAnimNodeDumpIntervalFrames", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeCapturesPerFrame", "15. Debug Overlay", "Bounded overlay work and memory budgets. Zero disables the corresponding capture/upload/draw stream where noted.\nRanges: captures 0..32, compound slots 1..1024, depth 1..8, queued/completed 0..256,\nuploads 0..16, cache entries 16..4096, cache bytes 1048576..536870912,\nbody instances 0..171, line vertices 0..65536, text vertices 0..131072.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxConvexSupportVertices", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxCompoundChildren", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxCompoundDepth", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeQueuedJobs", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeCompletedJobs", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeUploadsPerFrame", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeCacheEntries", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxShapeCacheBytes", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxBodyInstances", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxLineVertices", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxTextVertices", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugUseBoundsForHeavyConvex", "15. Debug Overlay", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugVerboseLogging", "16. Logs and Telemetry", "Very noisy per-frame diagnostic logging. Use only while investigating a specific issue.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabFrameLogging", "16. Logs and Telemetry", "Focused logs for grab frame capture and held-object transform comparisons.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugVideoSyncMarker", "16. Logs and Telemetry", "Optional video synchronization marker used only during diagnostics.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDebugVideoSyncMarkerSize", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabTimelineTrace", "16. Logs and Telemetry", "Structured per-grab timeline rows for capture, constraint writes, solver response, and release.\nUse this when building graphs from ROCK.log. Very noisy when enabled.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugGrabTimelineTraceIntervalFrames", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabAfterSolveAnomalySampling", "16. Logs and Telemetry", "Sample after-solve proxy/body mismatch diagnostics without enabling full grab-frame logging.\nThis reads live body and constraint atom state; keep disabled during normal gameplay.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetry", "16. Logs and Telemetry", "Timestamp-matched grab telemetry for comparing video, overlay text, and ROCK.log rows.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryText", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugGrabTransformTelemetryAxes", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryLogIntervalFrames", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugGrabTransformTelemetryTextMode", "16. Logs and Telemetry", "0 = duplicate telemetry text into both VR eye halves.\n1 = draw one text panel across the submitted texture.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowGrabNotifications", "16. Logs and Telemetry", "In-game popup diagnostics for grab decisions.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowWeaponNotifications", "16. Logs and Telemetry", "In-game popup diagnostics for weapon contact and support grip decisions.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugWeaponOmodDump", "16. Logs and Telemetry", "One-shot research dump per equipped weapon build: installed OMOD records\n(attach point, model path), generated evidence bindings, and the assembled\nweapon node tree. Verbose; enable only when collecting part-identity data.\nAlso writes bounded 10mm/SMG/pipe alignment and scale phase traces to\nROCK_WeaponAlignment.log. Enable before starting a game session.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugHandTransformParity", "16. Logs and Telemetry", "Compares ROCK's direct first-person skeleton hand transforms against the FRIK API path.\nDiagnostic only. It does not choose the active hand frame.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugHandWorldAuthority", "16. Logs and Telemetry", "Periodic summary of the FRIK API v2 hand world authority: controller-hand\nreconstruction source counts and error probe, claim rebase publishes, and\npre-FRIK scheduler state. Diagnostic only. Fallback and refusal warnings are\nalways logged.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugWorldObjectOriginDiagnostics", "16. Logs and Telemetry", "Logs and draws alternate world-origin candidates for selected or held objects.\nDiagnostic only. It does not change object motion.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugWorldObjectOriginLogIntervalFrames", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDebugWorldObjectOriginMismatchWarnGameUnits", "16. Logs and Telemetry", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowRootFlattenedFingerSkeletonMarkers", "17. Skeleton Debug", "Draws markers and axes for live first-person skeleton bones.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugShowSkeletonBoneVisualizer", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugSkeletonBoneMode", "17. Skeleton Debug", "0 = minimal/core bones, 1 = core body and fingers, higher modes may draw more if supported.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugSkeletonBoneSource", "17. Skeleton Debug", "Selects the skeleton source used by the debug visualizer.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxSkeletonBonesDrawn", "17. Skeleton Debug", "Draw limits and filters for skeleton debug drawing.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugDrawSkeletonBoneAxes", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugMaxSkeletonBoneAxesDrawn", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sDebugSkeletonAxisBoneFilter", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugLogSkeletonBones", "17. Skeleton Debug", "Logs bone names and truncation information to ROCK.log.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bDebugLogSkeletonBoneTruncation", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iDebugSkeletonBoneLogIntervalFrames", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "sDebugSkeletonBoneLogFilter", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDebugRootFlattenedFingerSkeletonMarkerSize", "17. Skeleton Debug", "Marker and axis sizes for skeleton debug visuals.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDebugSkeletonBonePointSize", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fDebugSkeletonBoneAxisLength", "17. Skeleton Debug", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "bHavokTimingFixEnabled", "18. Physics Timing", "Stabilizes FO4VR physics timing when rendering falls below the reference rate.", configuration_api::Group::Developer },
        { "PhysicsInteraction", "fHavokTimingFixMinPhysicsFrameRate", "18. Physics Timing", "", configuration_api::Group::Developer },
        { "PhysicsInteraction", "iHavokTimingFixMaxSubsteps", "18. Physics Timing", "", configuration_api::Group::Developer },
    };
}
