#pragma once

// Generated by tools/generate_grab_finger_calibration.py. Do not edit by hand.
// Source authority:
// - main_projects/hFRIK/src/skeleton/HandPose.cpp
// - main_projects/hFRIK/src/skeleton/HandPoseData.cpp
// Source SHA-256: 5c3fc5ca755efbf723b72152450ff2049006396c233179b07184b50c57123503

#include <array>
#include <cstddef>
#include <cstdint>

namespace rock::grab_finger_calibration_data
{
    inline constexpr std::uint32_t kGrabFingerCalibrationGeneratorVersion = 4;
    inline constexpr std::size_t kGrabFingerCalibrationSampleCount = 201;
    inline constexpr const char* kGrabFingerCalibrationSourceHash = "5c3fc5ca755efbf723b72152450ff2049006396c233179b07184b50c57123503";

    enum class BakedGrabFingerProbe : std::uint8_t
    {
        Tip,
        Outer,
        Inner
    };

    struct BakedGrabFingerCurveSample
    {
        float openValue = 1.0f;
        float angleRadians = 0.0f;
        float reachScale = 1.0f;
    };

    struct BakedGrabFingerProbeCurve
    {
        BakedGrabFingerProbe probe = BakedGrabFingerProbe::Tip;
        std::array<BakedGrabFingerCurveSample, kGrabFingerCalibrationSampleCount> samples{};
    };

    struct BakedGrabFingerCurve
    {
        float normalSign = 1.0f;
        float surfaceThicknessScale = 0.05f;
        std::array<BakedGrabFingerProbeCurve, 3> probes{};
    };

    enum class BakedGrabThumbLane : std::uint8_t
    {
        Wrap,
        Opposition,
        SidePad
    };

    enum class BakedGrabThumbCurveSource : std::uint8_t
    {
        HandThumb,
        SidePad
    };

    struct BakedGrabThumbLaneCurve
    {
        BakedGrabThumbLane lane = BakedGrabThumbLane::Wrap;
        BakedGrabThumbCurveSource curveSource = BakedGrabThumbCurveSource::HandThumb;
        float normalBlend = 0.0f;
        float localCorrectionStrength = 0.0f;
        float surfaceThicknessScale = 0.06f;
        bool applyAuthoredNormalSign = true;
    };

    struct BakedGrabFingerHandProfile
    {
        bool isLeft = false;
        bool inPowerArmor = false;
        std::array<BakedGrabFingerCurve, 5> fingers{};
    };

    struct BakedGrabThumbProfile
    {
        bool isLeft = false;
        bool inPowerArmor = false;
        std::array<BakedGrabThumbLaneCurve, 3> lanes{};
        BakedGrabFingerCurve sidePadCurve{};
    };

    [[nodiscard]] const BakedGrabFingerHandProfile& bakedGrabFingerHandProfile(bool isLeft, bool inPowerArmor) noexcept;
    [[nodiscard]] const BakedGrabThumbProfile& bakedGrabThumbProfile(bool isLeft, bool inPowerArmor) noexcept;
}
