# Post-Build event script to package the mod into a .7z file ONLY for release builds

string(TOLOWER "${CONFIG}" CONFIG_LOWER)
if(NOT CONFIG_LOWER STREQUAL "release")
  message("Skipping post-build packaging: not a release build: '${CONFIG}'")
  return()
endif()

set(PACKAGE_DIR "${BUILD_DIR}/package")
set(PACKAGE_STAGE_DIR "${PACKAGE_DIR}/stageing")
set(PACKAGE_STAGE_PLUGINS_DIR "${PACKAGE_STAGE_DIR}/F4SE/Plugins")
set(PACKAGE_STAGE_SDK_DIR "${PACKAGE_STAGE_DIR}/SDK")
string(TIMESTAMP PACKAGE_DATE "%Y%m%d")
set(TARGET_ZIP "${PACKAGE_DIR}/${PROJECT_FRIENDLY_NAME} - v${PROJECT_VERSION} - ${PACKAGE_DATE}.7z")

message("Packaging release build into '${TARGET_ZIP}'")
file(REMOVE_RECURSE "${PACKAGE_STAGE_DIR}")
file(MAKE_DIRECTORY "${PACKAGE_STAGE_PLUGINS_DIR}")
file(MAKE_DIRECTORY "${PACKAGE_STAGE_SDK_DIR}")
if(EXISTS "${ROOT_DIR}/data/mod")
  file(COPY "${ROOT_DIR}/data/mod/" DESTINATION "${PACKAGE_STAGE_DIR}")
endif()
file(COPY "${TARGET_FILE}" DESTINATION "${PACKAGE_STAGE_PLUGINS_DIR}")
file(COPY "${TARGET_PDB_FILE}" DESTINATION "${PACKAGE_STAGE_PLUGINS_DIR}")
if(EXISTS "${ROOT_DIR}/SDK/ROCK")
  file(COPY "${ROOT_DIR}/SDK/ROCK" DESTINATION "${PACKAGE_STAGE_SDK_DIR}")
endif()
file(MAKE_DIRECTORY "${PACKAGE_STAGE_SDK_DIR}/ROCK/include")
file(COPY "${ROOT_DIR}/src/api/ROCKProviderApi.h" DESTINATION "${PACKAGE_STAGE_SDK_DIR}/ROCK/include")
file(COPY "${ROOT_DIR}/src/api/ROCKApi.h" DESTINATION "${PACKAGE_STAGE_SDK_DIR}/ROCK/include")

execute_process(COMMAND ${CMAKE_COMMAND} -E tar cf "${TARGET_ZIP}" --format=7zip -- . WORKING_DIRECTORY "${PACKAGE_STAGE_DIR}")
