# CMake owns target/source discovery. The selector reads this catalog instead
# of interpreting CMake source syntax or assuming one source per executable.
function(add_rock_test TARGET_NAME)
  add_test(NAME ${TARGET_NAME} COMMAND $<TARGET_FILE:${TARGET_NAME}>)
  set_tests_properties(${TARGET_NAME} PROPERTIES LABELS "policy" TIMEOUT 30)
  add_dependencies(ROCKPolicyTestBinaries ${TARGET_NAME})
  if(MSVC)
    target_compile_options(${TARGET_NAME} PRIVATE /UNDEBUG)
  else()
    target_compile_options(${TARGET_NAME} PRIVATE -UNDEBUG)
  endif()

  get_target_property(TEST_SOURCES ${TARGET_NAME} SOURCES)
  set(SOURCE_JSON "[]")
  set(INDEX 0)
  foreach(SOURCE IN LISTS TEST_SOURCES)
    get_filename_component(SOURCE "${SOURCE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    file(TO_CMAKE_PATH "${SOURCE}" SOURCE)
    string(JSON SOURCE_JSON SET "${SOURCE_JSON}" ${INDEX} "\"${SOURCE}\"")
    math(EXPR INDEX "${INDEX} + 1")
  endforeach()
  get_property(CATALOG GLOBAL PROPERTY ROCK_POLICY_CATALOG)
  if(NOT CATALOG)
    set(CATALOG "{}")
  endif()
  string(JSON CATALOG SET "${CATALOG}" "${TARGET_NAME}" "${SOURCE_JSON}")
  set_property(GLOBAL PROPERTY ROCK_POLICY_CATALOG "${CATALOG}")
endfunction()

function(rock_write_test_catalog)
  get_property(CATALOG GLOBAL PROPERTY ROCK_POLICY_CATALOG)
  file(SHA256 "${ROOT_DIR}/CMakeLists.txt" CMAKE_HASH)
  file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_FILE}" REGISTRATION_HASH)
  file(WRITE "${BUILD_DIR}/RockTestCatalog.json"
    "{\"CMakeHash\":\"${CMAKE_HASH}\",\"RegistrationHash\":\"${REGISTRATION_HASH}\",\"Targets\":${CATALOG}}\n")
endfunction()
