# Validate the same trees consumed by deployment and packaging. Script mode is
# also used by the contract test with an isolated distribution fixture.
function(rock_verify_distribution_inputs)
  cmake_parse_arguments(INPUT "" "" "TREES;FILES" ${ARGN})
  set(FILES ${INPUT_FILES})
  foreach(TREE IN LISTS INPUT_TREES)
    if(EXISTS "${TREE}")
      file(GLOB_RECURSE TREE_FILES LIST_DIRECTORIES false "${TREE}/*")
      list(APPEND FILES ${TREE_FILES})
    endif()
  endforeach()
  foreach(PATH IN LISTS FILES)
    string(TOLOWER "${PATH}" LOWER_PATH)
    if(LOWER_PATH MATCHES "\\.ini$")
      message(FATAL_ERROR "Runtime or reference INI cannot be a distribution/build input: ${PATH}")
    endif()
    if(LOWER_PATH MATCHES "\\.rc$" AND EXISTS "${PATH}")
      file(READ "${PATH}" RESOURCE)
      string(TOLOWER "${RESOURCE}" RESOURCE)
      if(RESOURCE MATCHES "\"[^\"\n]*\\.ini\"")
        message(FATAL_ERROR "Resource script embeds an INI: ${PATH}")
      endif()
    endif()
  endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  rock_verify_distribution_inputs(TREES ${INPUT_TREES} FILES ${INPUT_FILES})
endif()
